#!/usr/bin/env python3
"""
batch15 → public/data/ja_articles.json

第1轮重写E: 4组场景 (8篇)
- n4-postoffice (邮局)
- n4-ward-office (区役所)
- n4-directions (问路)
- n4-repair (修理)

运行: python3 scripts/append_ja_articles_batch15.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import generate_ruby as gr  # noqa: E402


def full_reading(sentence: str) -> str:
    parts: list[str] = []
    for w in gr.tagger(sentence):
        k = w.feature.kana
        parts.append(gr.to_hira(k) if k else w.surface)
    return "".join(parts)


def seg(word: str, en: str, zh: str, paragraph_start: bool = False) -> dict:
    w = word.strip()
    d = {
        "word": w, "jp": w, "en": en.strip(), "zh": zh.strip(),
        "reading": full_reading(w), "ruby": gr.make_ruby(w),
    }
    if paragraph_start:
        d["paragraphStart"] = True
    return d


def line(speaker: str, word: str, en: str, zh: str) -> dict:
    d = seg(word, en, zh)
    d["speaker"] = speaker
    return d


def section(heading, heading_en, heading_zh, badge, lines_list):
    return {
        "badge": badge,
        "headingWord": heading, "headingJp": heading,
        "headingEn": heading_en, "headingZh": heading_zh,
        "lines": lines_list,
    }


NEW_ITEMS: list[dict] = [

    # ═══════════════════════════════════════════
    # 1. n4-postoffice 邮局
    # ═══════════════════════════════════════════
    {
        "id": "n4-postoffice-essay",
        "level": "N4–N3",
        "format": "essay",
        "titleWord": "郵便局で荷物を送る",
        "titleJp": "郵便局で荷物を送る",
        "titleEn": "Sending a package at the post office",
        "titleZh": "在邮局寄包裹",
        "titleRuby": [],
        "segments": [
            seg("実家の母に誕生日プレゼントを送ることにした。ネットで注文すれば楽だが、手紙も一緒に入れたかった。",
                "I decided to send a birthday present to my mother back home. Ordering online would be easier, but I wanted to include a letter.",
                "决定给老家的妈妈寄生日礼物。网上下单更轻松，但想把信也放进去。", True),
            seg("プレゼントはマフラーとハンドクリームを選んだ。百貨店で買って、きれいに包んでもらった。",
                "I chose a scarf and hand cream as presents. I bought them at a department store and had them gift-wrapped.",
                "礼物选了围巾和护手霜。在百货店买的，让人包装好了。"),
            seg("家でダンボール箱に詰めた。隙間には新聞紙を丸めて入れた。壊れやすいものはないが、念のためだ。",
                "At home I packed them in a cardboard box. I stuffed crumpled newspaper in the gaps. Nothing fragile, but just in case.",
                "在家装进了纸箱。空隙塞了揉成团的报纸。虽然没什么易碎品，但以防万一。"),
            seg("手紙を書いた。「お母さん、誕生日おめでとう。体に気をつけてね」。短いけど、気持ちは伝わるだろう。",
                "I wrote a letter. 'Happy birthday, Mom. Take care of yourself.' Short, but I'm sure the feeling comes through.",
                "写了封信。「妈妈生日快乐。注意身体」。虽然短，但心意应该能传达到。", True),
            seg("駅前の郵便局に行った。平日の午前中だったが、窓口には五人ほど並んでいた。",
                "I went to the post office near the station. It was a weekday morning, but about five people were lined up at the counter.",
                "去了车站前的邮局。虽然是工作日上午，窗口还排了五个人左右。"),
            seg("番号札を取って待った。電光掲示板に番号が表示されるシステムだ。",
                "I took a number ticket and waited. Numbers are displayed on an electronic board.",
                "取了号码牌等着。号码显示在电子屏上。"),
            seg("十分ほど待って、窓口に呼ばれた。荷物を出すと、職員が重さを量ってくれた。",
                "After about ten minutes I was called to the counter. I handed over the package and the clerk weighed it.",
                "等了十分钟左右被叫到窗口。把包裹递过去，工作人员称了重量。", True),
            seg("「ゆうパックでよろしいですか」と聞かれた。「はい、お願いします」と答えた。",
                "'Would you like to send it by Yu-Pack?' I was asked. 'Yes, please,' I answered.",
                "「用邮包可以吗」被问到。「好的，麻烦了」。"),
            seg("送り状に自分の名前と住所、相手の名前と住所を書いた。母の住所は暗記している。",
                "I wrote my name and address and the recipient's name and address on the shipping label. I have my mother's address memorized.",
                "在快递单上写了自己和对方的姓名地址。妈妈的地址早就背下来了。"),
            seg("「中身は何ですか」と聞かれたので、「衣類と化粧品です」と答えた。",
                "'What are the contents?' I was asked, so I said 'Clothing and cosmetics.'",
                "问了「里面是什么」，回答说「衣服和化妆品」。"),
            seg("「割れ物はありますか」「ありません」。「届け日の指定はありますか」「来週の水曜日にお願いします」。",
                "'Any fragile items?' 'No.' 'Would you like to specify a delivery date?' 'Next Wednesday, please.'",
                "「有易碎品吗」「没有」。「要指定到达日期吗」「下周三」。", True),
            seg("料金は千百五十円だった。距離によって値段が変わるらしい。東京から大阪なので、そこまで高くない。",
                "The fee was 1,150 yen. Apparently the price varies by distance. From Tokyo to Osaka, it wasn't too expensive.",
                "费用一千一百五十日元。好像根据距离价格不同。从东京到大阪，不算太贵。"),
            seg("支払いはクレジットカードでできた。昔は現金だけだった気がするが、便利になった。",
                "I could pay by credit card. I think it used to be cash only, but it's gotten more convenient.",
                "可以刷信用卡。以前好像只能付现金，方便多了。"),
            seg("領収書とお問い合わせ番号をもらった。番号があれば、ネットで配送状況を追跡できる。",
                "I received a receipt and a tracking number. With the number I can track the delivery status online.",
                "拿到了收据和查询号码。有号码就能在网上追踪配送状态。", True),
            seg("ついでに切手も買った。最近は手紙を書く機会が減ったが、年賀状の季節に使う。",
                "While I was there, I also bought stamps. I rarely write letters these days, but I use them for New Year's cards.",
                "顺便还买了邮票。最近写信的机会少了，但过年贺卡的时候用。"),
            seg("郵便局を出ると、赤いポストが目に入った。子どもの頃、ここに手紙を入れるのが楽しかった。",
                "Leaving the post office, I noticed the red mailbox. As a child, it was fun to drop letters in there.",
                "出了邮局，看到红色的邮筒。小时候往里面投信很开心。"),
            seg("二日後、母から電話があった。「届いたよ、ありがとう。マフラー、すごく暖かい」。声が嬉しそうだった。",
                "Two days later, my mother called. 'It arrived, thank you. The scarf is really warm.' She sounded happy.",
                "两天后妈妈打来电话。「收到了，谢谢。围巾好暖和」。声音听起来很高兴。", True),
            seg("「手紙も読んだよ。泣いちゃった」と言われて、送ってよかったと思った。",
                "'I read the letter too. I cried,' she said, and I was glad I sent it.",
                "「信也看了。看哭了」她说，觉得寄出去真好。"),
            seg("ネットの注文は便利だけど、自分で包んで手紙を添えると、気持ちが伝わりやすい気がする。",
                "Online orders are convenient, but wrapping it yourself and adding a letter seems to convey feelings better.",
                "网上下单虽然方便，但自己包装再附上信，感觉心意更容易传达。"),
            seg("来月は父の日だ。今度は父にも何か送ろう。",
                "Next month is Father's Day. I'll send something to Dad too.",
                "下个月是父亲节。这次也给爸爸寄点什么吧。"),
        ],
    },

    {
        "id": "n4-postoffice-dialogue",
        "level": "N4–N3",
        "format": "dialogue",
        "titleWord": "郵便局の窓口で",
        "titleJp": "郵便局の窓口で",
        "titleEn": "At the post office counter",
        "titleZh": "在邮局窗口",
        "titleRuby": [],
        "sections": [
            section("荷物を出す", "Sending a package", "寄包裹", "📦", [
                line("A", "すみません、この荷物を大阪まで送りたいんですけど。",
                     "Excuse me, I'd like to send this package to Osaka.",
                     "不好意思，想把这个包裹寄到大阪。"),
                line("B", "ゆうパックでよろしいですか？",
                     "Would Yu-Pack be OK?",
                     "用邮包可以吗？"),
                line("A", "はい、お願いします。あの、届け日って指定できますか？",
                     "Yes, please. Um, can I specify the delivery date?",
                     "好的。那个，可以指定到达日期吗？"),
                line("B", "はい、できますよ。いつがよろしいですか？",
                     "Yes, you can. When would you like?",
                     "可以的。什么时候？"),
                line("A", "来週の水曜日にお願いします。母の誕生日なんです。",
                     "Next Wednesday, please. It's my mother's birthday.",
                     "下周三。是我妈妈的生日。"),
                line("B", "承知しました。時間帯の指定もできますが、どうされますか？午前中とか。",
                     "Understood. You can also specify a time window. Morning, for example?",
                     "好的。也可以指定时间段，怎么样？比如上午。"),
                line("A", "じゃあ午前中でお願いします。確実に家にいると思うので。",
                     "Then morning, please. She should definitely be home.",
                     "那就上午吧。应该肯定在家。"),
            ]),
            section("送り状を書く", "Filling out the label", "填快递单", "📝", [
                line("B", "では、こちらの送り状にご記入お願いします。送り主と届け先のお名前とご住所を。",
                     "Then please fill out this shipping label. Your name and address, and the recipient's.",
                     "那请在这张快递单上填一下。寄件人和收件人的姓名地址。"),
                line("A", "はい。……あの、品名って何て書けばいいですか？",
                     "OK. ...Um, what should I write for the item description?",
                     "好。……那个，品名怎么写？"),
                line("B", "中に何が入っていますか？",
                     "What's inside?",
                     "里面装的什么？"),
                line("A", "マフラーとハンドクリームです。プレゼントなんですけど。",
                     "A scarf and hand cream. They're a present.",
                     "围巾和护手霜。是礼物。"),
                line("B", "じゃあ「衣類・化粧品」と書いてください。壊れ物はありますか？",
                     "Then please write 'Clothing/Cosmetics.' Any fragile items?",
                     "那写「衣物·化妆品」。有易碎品吗？"),
                line("A", "ないです。",
                     "No.",
                     "没有。"),
                line("B", "分かりました。重さを量りますね。……千百五十円になります。",
                     "Got it. Let me weigh it. ...That'll be 1,150 yen.",
                     "好的。称一下。……一千一百五十日元。"),
            ]),
            section("支払いと確認", "Payment and confirmation", "付款和确认", "💳", [
                line("A", "カードで払えますか？",
                     "Can I pay by card?",
                     "能刷卡吗？"),
                line("B", "はい、クレジットカードでも電子マネーでも大丈夫です。",
                     "Yes, credit card or electronic money, either is fine.",
                     "可以的，信用卡和电子支付都行。"),
                line("A", "じゃあカードで。……あ、追跡番号ってもらえますか？",
                     "Then by card. ...Oh, can I get a tracking number?",
                     "那刷卡。……对了，能给追踪号码吗？"),
                line("B", "はい、こちらの控えに番号が載っています。ネットで配送状況を確認できますよ。",
                     "Yes, the number is on this receipt copy. You can check the delivery status online.",
                     "有的，在这张回执上写着号码。可以在网上查配送状态。"),
                line("A", "ありがとうございます。ちゃんと届くか心配なので、見てみます。",
                     "Thank you. I'm worried about whether it'll arrive safely, so I'll check.",
                     "谢谢。担心能不能顺利到，看看。"),
                line("B", "水曜日の午前中にお届けしますので、ご安心ください。ほかにご用はありますか？",
                     "It will be delivered Wednesday morning, so please don't worry. Is there anything else?",
                     "周三上午送达，请放心。还有别的事吗？"),
                line("A", "あ、八十四円の切手を五枚ください。",
                     "Oh, five 84-yen stamps please.",
                     "啊，再买五张八十四日元的邮票。"),
                line("B", "はい、五枚で四百二十円です。合計千五百七十円になります。",
                     "OK, five stamps for 420 yen. That's a total of 1,570 yen.",
                     "好的，五张四百二十日元。一共一千五百七十日元。"),
            ]),
        ],
    },

    # ═══════════════════════════════════════════
    # 2. n4-ward-office 区役所
    # ═══════════════════════════════════════════
    {
        "id": "n4-ward-office-essay",
        "level": "N4–N3",
        "format": "essay",
        "titleWord": "区役所で住民票を取る",
        "titleJp": "区役所で住民票を取る",
        "titleEn": "Getting a residence certificate at the ward office",
        "titleZh": "在区役所办住民票",
        "titleRuby": [],
        "segments": [
            seg("新しいクレジットカードを作るために、住民票が必要になった。本人確認の書類として求められたのだ。",
                "I needed a residence certificate to apply for a new credit card. It was required as an identity verification document.",
                "办新信用卡需要住民票。作为身份确认材料被要求提供。", True),
            seg("住民票は区役所で取れる。コンビニでも取れるらしいが、マイナンバーカードの暗証番号を忘れてしまった。",
                "You can get a residence certificate at the ward office. Apparently you can also get one at a convenience store, but I forgot my My Number card PIN.",
                "住民票在区役所能办。据说便利店也能办，但我忘了个人编号卡的密码。"),
            seg("仕方なく、区役所に行くことにした。平日に休みを取るのは面倒だが、土曜日もやっていると聞いた。",
                "I had no choice but to go to the ward office. Taking a weekday off is a hassle, but I heard they're open on Saturdays too.",
                "只好去区役所。工作日请假麻烦，但听说周六也开。"),
            seg("土曜日の朝九時に区役所に着いた。入り口に案内の人が立っていた。",
                "I arrived at the ward office at 9 AM Saturday. A guide was standing at the entrance.",
                "周六早上九点到了区役所。入口有引导员站着。", True),
            seg("「何のご用件ですか」と聞かれたので、「住民票をもらいに来ました」と答えた。",
                "'What are you here for?' they asked. 'I came to get a residence certificate,' I answered.",
                "「办什么业务」被问到。「来拿住民票」。"),
            seg("「二階の窓口へどうぞ。番号札を取ってお待ちください」と言われた。",
                "'Please go to the counter on the second floor. Take a number ticket and wait,' I was told.",
                "「请去二楼窗口。取号码牌等候」。"),
            seg("二階に上がると、広い待合スペースがあった。椅子がたくさん並んでいて、すでに十人ほど待っていた。",
                "Going up to the second floor, there was a wide waiting area. Lots of chairs were lined up, and about ten people were already waiting.",
                "上了二楼，有很大的等候区。排了很多椅子，已经有十来个人在等了。"),
            seg("番号札を取ると、四十二番だった。電光掲示板を見ると、今は三十五番が呼ばれている。七人待ちだ。",
                "My number ticket was 42. The electronic board showed number 35 being called. Seven people ahead.",
                "取了号码牌是四十二号。电子屏显示现在叫到三十五号。前面还有七个人。", True),
            seg("待っている間にスマホでニュースを読んだ。区役所のWi-Fiが使えたので助かった。",
                "While waiting I read news on my phone. The ward office Wi-Fi was available, which helped.",
                "等的时候用手机看了新闻。区役所有Wi-Fi，方便。"),
            seg("二十分ほど待って、やっと番号が呼ばれた。窓口に行くと、申請書を渡された。",
                "After about twenty minutes, my number was finally called. At the counter I was given an application form.",
                "等了二十分钟左右终于叫到号了。去了窗口，拿到了申请表。"),
            seg("名前と住所と生年月日を書いて、必要な項目にチェックを入れた。「世帯全員」か「本人のみ」を選ぶ欄がある。",
                "I wrote my name, address, and date of birth, and checked the required boxes. There's a field to choose 'entire household' or 'self only.'",
                "填了姓名地址出生日期，勾选了需要的项目。有一栏选「全家」或「仅本人」。"),
            seg("本人確認のために免許証を見せた。職員がコピーを取って、返してくれた。",
                "I showed my driver's license for ID verification. The clerk made a copy and returned it.",
                "出示了驾照做身份确认。工作人员复印了一份还给了我。", True),
            seg("「少々お待ちください」と言われて、五分ほど待った。住民票を印刷しているのだろう。",
                "'Please wait a moment,' I was told, and waited about five minutes. They were probably printing the certificate.",
                "「请稍等」被告知，等了五分钟。应该是在打印住民票。"),
            seg("住民票を受け取った。三百円。コンビニなら二百円で取れるそうだ。暗証番号を再設定しておこう。",
                "I received the certificate. 300 yen. At a convenience store it's only 200 yen, I hear. I should reset my PIN.",
                "拿到了住民票。三百日元。便利店好像两百就能办。得去重新设定密码。"),
            seg("ついでに一階のマイナンバーの窓口に寄って、暗証番号の再設定もしてもらった。",
                "While I was there, I stopped by the My Number counter on the first floor and had my PIN reset.",
                "顺便去了一楼的个人编号窗口，让他们帮忙重设了密码。", True),
            seg("これで次からはコンビニで住民票が取れる。わざわざ区役所に来なくて済む。",
                "Now I can get a residence certificate at a convenience store next time. No need to come all the way to the ward office.",
                "这下下次就能在便利店办住民票了。不用特意跑一趟区役所。"),
            seg("区役所を出たのは十時半だった。思ったより早く終わった。土曜日でも意外とスムーズだ。",
                "I left the ward office at 10:30. It finished sooner than expected. Surprisingly smooth even on Saturday.",
                "出区役所的时候十点半。比想象中快。周六居然也挺顺利。"),
            seg("帰りにコンビニでコーヒーを買った。一つ用事が片付くと気分がいい。",
                "On the way home I bought coffee at a convenience store. Getting an errand done feels good.",
                "回去路上在便利店买了杯咖啡。办完一件事心情就好。"),
            seg("住民票はクレジットカードの申し込みに使って、残りは大事に保管しておこう。",
                "I'll use the certificate for the credit card application and keep the rest safely stored.",
                "住民票用来申请信用卡，剩下的好好保管。"),
            seg("役所の手続きは面倒だと思っていたが、やってみるとそれほど大変ではなかった。",
                "I thought government paperwork would be a pain, but once I tried it, it wasn't that bad.",
                "本以为去政府办事很麻烦，实际上也没那么难。"),
        ],
    },

    {
        "id": "n4-ward-office-dialogue",
        "level": "N4–N3",
        "format": "dialogue",
        "titleWord": "区役所の窓口で手続きする",
        "titleJp": "区役所の窓口で手続きする",
        "titleEn": "Doing paperwork at the ward office",
        "titleZh": "在区役所窗口办手续",
        "titleRuby": [],
        "sections": [
            section("案内で聞く", "Asking at the info desk", "在咨询台问", "🏢", [
                line("A", "すみません、住民票を取りたいんですけど、どこに行けばいいですか？",
                     "Excuse me, I'd like to get a residence certificate — where should I go?",
                     "不好意思，想办住民票，去哪里？"),
                line("B", "住民票は二階の三番窓口です。こちらの番号札を取ってお待ちくださいね。",
                     "Residence certificates are at counter 3 on the second floor. Please take a number ticket and wait.",
                     "住民票在二楼三号窗口。拿这个号码牌等一下。"),
                line("A", "だいたいどのくらい待ちますか？",
                     "About how long is the wait?",
                     "大概等多久？"),
                line("B", "今日は土曜日なので少し混んでいます。二十分くらいでしょうか。",
                     "It's Saturday so it's a bit crowded. Maybe about twenty minutes.",
                     "今天周六人多一些。大概二十分钟吧。"),
                line("A", "分かりました。あ、本人確認の書類って何が要りますか？",
                     "OK. Oh, what do I need for ID verification?",
                     "好的。对了，身份证明需要什么？"),
                line("B", "免許証かマイナンバーカードがあれば大丈夫ですよ。保険証の場合はもう一点必要になります。",
                     "A driver's license or My Number card is fine. If you use a health insurance card, you'll need one more piece of ID.",
                     "有驾照或个人编号卡就行。用保险证的话需要再加一样。"),
                line("A", "免許証あります。ありがとうございます。",
                     "I have my driver's license. Thank you.",
                     "有驾照。谢谢。"),
            ]),
            section("窓口で申請", "Applying at the counter", "在窗口申请", "📋", [
                line("C", "四十二番の方、お待たせしました。どうぞ。",
                     "Number 42, sorry for the wait. Please come forward.",
                     "四十二号，让您久等了。请过来。"),
                line("A", "住民票をお願いしたいんですけど。",
                     "I'd like a residence certificate.",
                     "想办住民票。"),
                line("C", "はい。こちらの申請書にご記入ください。世帯全員分ですか、ご本人のみですか？",
                     "Sure. Please fill out this form. For the entire household or just yourself?",
                     "好的。请填这张申请表。全家的还是只要本人？"),
                line("A", "本人だけで大丈夫です。あ、マイナンバーって載せた方がいいですか？",
                     "Just myself is fine. Oh, should I include my My Number?",
                     "只要本人就行。对了，要不要写个人编号？"),
                line("C", "使い道によりますが、クレジットカードの申し込みでしたら、載せなくても大丈夫ですよ。",
                     "It depends on the purpose, but if it's for a credit card application, you don't need to include it.",
                     "看用途，如果是申请信用卡的话不写也行。"),
                line("A", "じゃあ載せないでお願いします。",
                     "Then without it, please.",
                     "那就不写了。"),
                line("C", "分かりました。本人確認をしますので、免許証を見せていただけますか？",
                     "Got it. I'll verify your identity, so may I see your license?",
                     "好的。需要确认身份，能看一下驾照吗？"),
            ]),
            section("受け取り", "Receiving the certificate", "领取", "✅", [
                line("C", "お待たせしました。こちらが住民票です。内容をご確認ください。",
                     "Sorry for the wait. Here's your certificate. Please check the contents.",
                     "让您久等了。这是住民票。请确认一下内容。"),
                line("A", "……はい、合ってます。料金はいくらですか？",
                     "...Yes, it's correct. How much is the fee?",
                     "……嗯，没问题。多少钱？"),
                line("C", "一通三百円になります。お支払いは現金でもカードでも大丈夫です。",
                     "It's 300 yen per copy. Cash or card is fine.",
                     "一份三百日元。现金或刷卡都行。"),
                line("A", "カードで。あの、ついでに聞きたいんですけど、マイナンバーカードの暗証番号を忘れちゃったんですけど……。",
                     "By card. Also, I'd like to ask — I forgot my My Number card PIN...",
                     "刷卡。还有想问一下，个人编号卡的密码忘了……"),
                line("C", "再設定できますよ。一階のマイナンバー窓口で手続きしてください。本人確認書類があればすぐできます。",
                     "You can have it reset. Please go to the My Number counter on the first floor. It's quick if you have an ID.",
                     "可以重设。去一楼个人编号窗口办理。有身份证明的话很快。"),
                line("A", "助かります。じゃあこのあと行ってみます。ありがとうございました。",
                     "That helps. I'll go there after this then. Thank you very much.",
                     "太好了。那等下去看看。谢谢。"),
                line("C", "どういたしまして。お気をつけて。",
                     "You're welcome. Take care.",
                     "不客气。慢走。"),
            ]),
        ],
    },

    # ═══════════════════════════════════════════
    # 3. n4-directions 问路
    # ═══════════════════════════════════════════
    {
        "id": "n4-directions-essay",
        "level": "N4–N3",
        "format": "essay",
        "titleWord": "知らない街で道に迷う",
        "titleJp": "知らない街で道に迷う",
        "titleEn": "Getting lost in an unfamiliar town",
        "titleZh": "在陌生的街道迷路",
        "titleRuby": [],
        "segments": [
            seg("友達の結婚式に出席するため、初めて横浜に来た。式場は駅から歩いて十五分のはずだった。",
                "I came to Yokohama for the first time to attend a friend's wedding. The venue was supposed to be a 15-minute walk from the station.",
                "为了参加朋友的婚礼第一次来横浜。会场应该离车站走十五分钟。", True),
            seg("駅を出たが、東口と西口を間違えてしまった。地図アプリを開いたが、GPSがうまく動かない。",
                "I exited the station but mixed up the east and west exits. I opened the map app but the GPS wasn't working properly.",
                "出了车站，但东口西口搞反了。打开地图App，GPS不太好使。"),
            seg("ビルの間を歩いていると、だんだん景色が分からなくなった。同じような建物ばかりで、どこにいるのか分からない。",
                "Walking between buildings, the scenery became increasingly unfamiliar. All the buildings looked the same and I couldn't tell where I was.",
                "走在楼房之间，越走越不认识了。建筑物都差不多，不知道自己在哪。"),
            seg("式は二時からだ。もう一時半になっている。このままだと遅刻する。",
                "The ceremony starts at two. It's already 1:30. At this rate I'll be late.",
                "婚礼两点开始。已经一点半了。再这样下去要迟到。", True),
            seg("焦って、近くのコンビニに入った。店員に「すみません、このホテルに行きたいんですが」と招待状を見せた。",
                "In a panic I went into a nearby convenience store. I showed the invitation to the clerk saying 'Excuse me, I'd like to get to this hotel.'",
                "着急之下进了附近的便利店。拿着请帖给店员看「不好意思，想去这个酒店」。"),
            seg("店員は若い女性で、スマホで調べてくれた。「ここからだと、反対方向ですね」と言われた。",
                "The clerk was a young woman who looked it up on her phone. 'From here, it's in the opposite direction,' she said.",
                "店员是位年轻女性，帮忙用手机查了。「从这里的话，要往反方向走」。"),
            seg("「この道をまっすぐ戻って、大きな交差点を右に曲がってください。五分くらいで着きますよ」。",
                "'Go straight back along this road and turn right at the big intersection. You'll be there in about five minutes.'",
                "「沿这条路直走回去，在大路口右转。大概五分钟就到」。", True),
            seg("お礼を言って走った。スーツを着て走るのは大変だが、遅刻するわけにはいかない。",
                "I thanked her and ran. Running in a suit is tough, but I can't be late.",
                "道了谢就跑了。穿着西装跑很辛苦，但不能迟到。"),
            seg("大きな交差点が見えた。右に曲がると、ホテルの看板が見えた。ほっとした。",
                "I saw the big intersection. I turned right and the hotel sign came into view. I was relieved.",
                "看到了大路口。右转后看到了酒店的招牌。松了口气。"),
            seg("ホテルに着いたのは一時五十五分。ぎりぎり間に合った。汗だくだったが。",
                "I arrived at the hotel at 1:55. Just barely in time. Though I was drenched in sweat.",
                "到酒店的时候一点五十五分。勉强赶上了。虽然满头大汗。", True),
            seg("トイレで顔を洗って、ハンカチで汗を拭いた。鏡を見ると、顔が真っ赤だった。",
                "I washed my face in the restroom and wiped the sweat with my handkerchief. Looking in the mirror, my face was bright red.",
                "在洗手间洗了把脸，用手帕擦了汗。一看镜子脸通红。"),
            seg("式場に入ると、友達が「ちょうどよかった！もうすぐ始まるよ」と言った。間に合ってよかった。",
                "When I entered the venue, my friend said 'Perfect timing! It's about to start.' Glad I made it.",
                "进了会场朋友说「正好！马上开始了」。赶上了真好。"),
            seg("結婚式はとても素敵だった。花嫁のドレスが美しくて、スピーチで泣いている人もいた。",
                "The wedding was lovely. The bride's dress was beautiful, and some people cried during the speeches.",
                "婚礼非常美好。新娘的婚纱很漂亮，致辞的时候有人哭了。", True),
            seg("披露宴では隣の席の人と楽しく話した。料理もおいしかった。",
                "At the reception I chatted happily with the person next to me. The food was delicious too.",
                "宴会上和旁边的人聊得很开心。菜也很好吃。"),
            seg("帰りは迷わないように、ホテルのフロントで駅までの道を教えてもらった。",
                "On the way back, I asked the hotel front desk for directions to the station so I wouldn't get lost.",
                "回去的时候怕再迷路，在酒店前台问了去车站的路。"),
            seg("「ホテルを出て左に曲がって、まっすぐ行けば駅です」。今度は迷わなかった。",
                "'Turn left out of the hotel and go straight — that's the station.' This time I didn't get lost.",
                "「出酒店左转直走就是车站」。这次没迷路。", True),
            seg("電車の中で、今日のことを振り返った。迷ったのは大変だったが、いい思い出になった。",
                "On the train I reflected on the day. Getting lost was stressful, but it became a good memory.",
                "在电车上回想今天的事。迷路虽然辛苦，但成了美好的回忆。"),
            seg("スマホの地図アプリの使い方を、もっと練習しておこうと思った。",
                "I thought I should practice using the map app on my phone more.",
                "想着得多练练手机地图App的用法。"),
            seg("そして知らない街に行くときは、時間に余裕を持って出発しようと反省した。",
                "And I reminded myself to leave with plenty of time when going to an unfamiliar place.",
                "还有反省了一下去陌生地方一定要提前多留时间出发。"),
            seg("でも道に迷ったおかげで、親切な店員さんに出会えた。人の優しさに触れるのは嬉しいものだ。",
                "But thanks to getting lost, I met a kind store clerk. Encountering people's kindness is a nice thing.",
                "不过正因为迷了路，才遇到了热心的店员。感受到别人的善意是件高兴的事。"),
        ],
    },

    {
        "id": "n4-directions-dialogue",
        "level": "N4–N3",
        "format": "dialogue",
        "titleWord": "道を聞く",
        "titleJp": "道を聞く",
        "titleEn": "Asking for directions",
        "titleZh": "问路",
        "titleRuby": [],
        "sections": [
            section("コンビニで聞く", "Asking at the convenience store", "在便利店问", "🏪", [
                line("A", "すみません、このホテルに行きたいんですけど、道が分からなくて……。",
                     "Excuse me, I'd like to get to this hotel but I don't know the way...",
                     "不好意思，想去这家酒店，但不知道怎么走……"),
                line("B", "あ、どれどれ。……ああ、ここですね。ここからだとちょっと反対方向に来ちゃってますね。",
                     "Oh, let me see. ...Ah, this one. You've come a bit in the opposite direction from here.",
                     "啊，让我看看。……这家啊。从这里的话你走反了。"),
                line("A", "えっ、反対ですか……。もう一時半なんですけど、間に合いますかね？",
                     "What, the opposite way... It's already 1:30, do you think I'll make it?",
                     "诶，走反了……已经一点半了，来得及吗？"),
                line("B", "大丈夫ですよ、五分くらいで着きます。この道をまっすぐ戻ってください。",
                     "You'll be fine, it's about five minutes. Go straight back along this road.",
                     "没问题的，五分钟左右就到。沿这条路直走回去。"),
                line("A", "まっすぐですね。",
                     "Straight ahead, right.",
                     "直走对吧。"),
                line("B", "はい。三百メートルくらい行くと大きな交差点があるので、そこを右に曲がってください。",
                     "Yes. After about 300 meters there's a big intersection, so turn right there.",
                     "对。走三百米左右有个大路口，在那右转。"),
                line("A", "大きな交差点を右ですね。",
                     "Right at the big intersection, got it.",
                     "大路口右转。"),
                line("B", "そうです。曲がったらすぐ左手にホテルが見えますよ。白い建物です。",
                     "That's right. After you turn, you'll see the hotel on your left right away. It's a white building.",
                     "对的。转弯后左手边马上就能看到酒店。白色的建筑。"),
            ]),
            section("確認する", "Double-checking", "再确认", "🗺", [
                line("A", "ありがとうございます。えっと、もう一回確認していいですか。まっすぐ戻って、大きな交差点を右……。",
                     "Thank you. Um, can I confirm once more? Go straight back, right at the big intersection...",
                     "谢谢。那个，能再确认一下吗。直走回去，大路口右转……"),
                line("B", "はい、そうです。信号のある大きな交差点です。ファミマが角にありますよ。",
                     "Yes, that's right. It's a big intersection with traffic lights. There's a FamilyMart on the corner.",
                     "对的。有红绿灯的大路口。拐角有全家便利店。"),
                line("A", "ファミマが目印ですね。分かりました。助かりました、本当にありがとうございます！",
                     "FamilyMart as the landmark, got it. You're a lifesaver, thank you so much!",
                     "全家做标记。明白了。帮大忙了，真的谢谢！"),
                line("B", "いえいえ。結婚式ですか？おめでたいですね。気をつけて行ってくださいね。",
                     "Not at all. A wedding? How wonderful. Take care on your way.",
                     "没什么。是婚礼吗？恭喜啊。路上小心。"),
                line("A", "はい！走っていきます！",
                     "Yes! I'll run there!",
                     "好的！跑过去！"),
            ]),
            section("たどり着く", "Arriving", "终于到了", "🎉", [
                line("C", "おっ、来た来た。ぎりぎりだね。汗すごいけど大丈夫？",
                     "Oh, you made it! Just barely. You're drenched in sweat — are you OK?",
                     "哦，来了来了。差点赶不上。一身汗没事吧？"),
                line("A", "道に迷ってさ……。東口と西口間違えて、反対方向に歩いちゃって。",
                     "I got lost... Mixed up the east and west exits and walked the wrong way.",
                     "迷路了……东口西口搞反了，往反方向走了。"),
                line("C", "あはは、横浜初めてだもんね。でも間に合ったからよかったじゃん。",
                     "Haha, it's your first time in Yokohama after all. But you made it, so that's good.",
                     "哈哈，毕竟第一次来横浜嘛。但赶上了就好。"),
                line("A", "うん、コンビニの店員さんが親切に教えてくれたんだよ。",
                     "Yeah, a convenience store clerk kindly gave me directions.",
                     "嗯，便利店的店员很热心地告诉我了。"),
                line("C", "次からはGoogleマップちゃんと使いなよ。ほら、もう始まるよ。",
                     "Use Google Maps properly next time. Come on, it's about to start.",
                     "下次好好用谷歌地图吧。快，要开始了。"),
                line("A", "はいはい。……あ、新婦きれいだね。",
                     "OK, OK. ...Oh, the bride is beautiful.",
                     "知道了知道了。……啊，新娘真漂亮。"),
            ]),
        ],
    },

    # ═══════════════════════════════════════════
    # 4. n4-repair 修理
    # ═══════════════════════════════════════════
    {
        "id": "n4-repair-essay",
        "level": "N4–N3",
        "format": "essay",
        "titleWord": "壊れたエアコンを修理してもらう",
        "titleJp": "壊れたエアコンを修理してもらう",
        "titleEn": "Getting a broken air conditioner repaired",
        "titleZh": "请人修坏了的空调",
        "titleRuby": [],
        "segments": [
            seg("七月に入って急に暑くなった。帰宅してエアコンのリモコンを押したが、反応がない。",
                "It suddenly got hot in July. I came home and pressed the air conditioner remote, but nothing happened.",
                "进入七月突然热了起来。回到家按了空调遥控器，没反应。", True),
            seg("電池を替えてみたが、やはり動かない。本体のランプも点かない。完全に壊れたようだ。",
                "I tried replacing the batteries but it still wouldn't work. The unit's light wouldn't turn on either. It seems completely broken.",
                "换了电池还是不行。机器上的灯也不亮。看来是彻底坏了。"),
            seg("このエアコンは五年前に買った。保証期間は過ぎている。修理するか、新しいのを買うか迷った。",
                "I bought this AC five years ago. The warranty has expired. I debated whether to repair it or buy a new one.",
                "这台空调是五年前买的。保修期已经过了。纠结是修还是买新的。"),
            seg("とりあえずメーカーのサポートに電話した。混んでいて、十五分待たされた。",
                "I called the manufacturer's support line for now. It was busy and I was kept waiting for fifteen minutes.",
                "先打了厂家的客服电话。很忙，等了十五分钟。", True),
            seg("症状を伝えると、「部品の交換が必要かもしれません。出張修理になります」と言われた。",
                "When I described the symptoms, they said 'Parts replacement may be needed. It will require an on-site repair visit.'",
                "说了症状后被告知「可能需要更换零件。需要上门维修」。"),
            seg("修理費は出張料込みで一万五千円から二万円くらい。新品は取り付け工事込みで八万円以上する。",
                "Repair costs are about 15,000 to 20,000 yen including the service call. A new unit costs over 80,000 yen including installation.",
                "维修费含上门费大概一万五到两万日元。新机加安装要八万以上。"),
            seg("まだ五年しか使っていないし、修理することにした。一番早い日程は三日後だった。",
                "I've only used it for five years, so I decided on repair. The earliest slot was three days later.",
                "才用了五年，决定修。最早的日程是三天后。"),
            seg("修理が来るまでの三日間が地獄だった。扇風機だけでは全然涼しくない。",
                "The three days waiting for the repair were hell. A fan alone isn't cool at all.",
                "等维修的三天简直是地狱。光靠电扇根本不凉快。", True),
            seg("夜は暑くて何度も目が覚めた。アイス枕を使って、なんとかしのいだ。",
                "At night I kept waking up from the heat. I got by using an ice pillow.",
                "晚上热得醒了好几次。用冰枕勉强撑过来了。"),
            seg("会社にいる間はエアコンがあるので天国だった。できれば帰りたくなかった。",
                "It was heaven at the office where there's AC. I didn't want to go home if I could help it.",
                "在公司有空调就是天堂。能不回家就不想回。"),
            seg("修理の日、午前中の指定で業者が来た。作業服を着た男性が一人で来た。",
                "On repair day, the technician came during the designated morning slot. A man in work clothes came alone.",
                "维修那天，上午时段师傅来了。穿工作服的男性一个人来的。", True),
            seg("エアコンのカバーを外して中を見た。「基板が焼けてますね。交換すれば直ります」と言われた。",
                "He removed the AC cover and looked inside. 'The circuit board is burnt. Replacing it will fix it,' he said.",
                "拆了空调外壳看了看里面。「主板烧了。换一块就能修好」。"),
            seg("部品は持ってきていたので、その場で交換してくれた。作業は三十分ほどで終わった。",
                "He had the part with him, so he replaced it on the spot. The work took about thirty minutes.",
                "零件带来了，当场就换了。作业大概三十分钟就结束了。"),
            seg("スイッチを入れると、冷たい風が出てきた。「直った！」と思わず声が出た。",
                "When I turned it on, cold air came out. I involuntarily blurted out 'It's fixed!'",
                "一开机，冷风吹出来了。忍不住喊了句「修好了！」", True),
            seg("修理費は一万八千円だった。カードで払った。高いが、新品を買うよりはずっと安い。",
                "The repair cost was 18,000 yen. I paid by card. Expensive, but much cheaper than buying new.",
                "维修费一万八千日元。刷卡付了。虽然贵，但比买新的便宜多了。"),
            seg("業者が帰った後、冷房の効いた部屋でしばらくぼーっとした。涼しいって幸せだ。",
                "After the technician left, I spaced out for a while in the cooled room. Being cool is happiness.",
                "师傅走后在冷气房里发了会儿呆。凉快真幸福。"),
            seg("フィルターの掃除もしてもらったので、風がきれいで気持ちいい。",
                "They also cleaned the filter, so the air was clean and comfortable.",
                "顺便帮忙清洗了过滤网，风很清新舒服。", True),
            seg("業者に「年に一回はフィルターを掃除した方がいいですよ」とアドバイスされた。全然やっていなかった。",
                "The technician advised me 'You should clean the filter at least once a year.' I hadn't been doing it at all.",
                "师傅建议「一年至少清洗一次过滤网」。完全没做过。"),
            seg("エアコンが壊れて初めて、普段どれだけエアコンに頼っているか分かった。",
                "Only when the AC broke did I realize how much I depend on it every day.",
                "空调坏了才明白平时有多依赖它。"),
            seg("これからはフィルターをちゃんと掃除して、大事に使おう。次の夏も乗り越えなければ。",
                "From now on I'll properly clean the filter and take good care of it. I have to survive next summer too.",
                "以后好好清洗过滤网，珍惜使用。下个夏天也得熬过去。"),
        ],
    },

    {
        "id": "n4-repair-dialogue",
        "level": "N4–N3",
        "format": "dialogue",
        "titleWord": "エアコンの修理を頼む",
        "titleJp": "エアコンの修理を頼む",
        "titleEn": "Requesting an AC repair",
        "titleZh": "预约空调维修",
        "titleRuby": [],
        "sections": [
            section("電話で予約", "Booking by phone", "电话预约", "📞", [
                line("A", "すみません、エアコンが動かなくなってしまったんですけど、修理をお願いしたくて。",
                     "Excuse me, my air conditioner stopped working and I'd like to request a repair.",
                     "不好意思，空调不动了，想预约维修。"),
                line("B", "ありがとうございます。型番と症状を教えていただけますか？",
                     "Thank you. Could you tell me the model number and symptoms?",
                     "谢谢。能告诉我型号和症状吗？"),
                line("A", "えっと、型番は……本体に貼ってあるやつですよね？ちょっと待ってください。……ABC二千です。",
                     "Um, the model number is... the one on the sticker on the unit, right? Hold on. ...It's ABC-2000.",
                     "嗯，型号是……贴在机器上的那个吧？稍等。……ABC-2000。"),
                line("B", "ありがとうございます。症状はどんな感じですか？",
                     "Thank you. What are the symptoms?",
                     "谢谢。症状是什么样的？"),
                line("A", "リモコンを押しても反応しないんです。電池は替えました。本体のランプもつかなくて。",
                     "It doesn't respond when I press the remote. I replaced the batteries. The unit's light won't turn on either.",
                     "按遥控器没反应。电池换过了。机器上的灯也不亮。"),
                line("B", "なるほど。基板の故障かもしれませんね。出張修理になりますが、一番早くて木曜日の午前中です。",
                     "I see. It might be a circuit board failure. It will need an on-site visit — the earliest is Thursday morning.",
                     "明白了。可能是主板故障。需要上门维修，最早是周四上午。"),
                line("A", "木曜日……三日後か。もっと早くはならないですか？この暑さで死にそうなんですけど。",
                     "Thursday... three days from now. Can't it be sooner? I'm dying in this heat.",
                     "周四……三天后啊。不能再早点吗？这么热快受不了了。"),
                line("B", "申し訳ございません、今の時期は混み合っておりまして。木曜の午前でご予約しますか？",
                     "I'm sorry, this time of year is very busy. Shall I book Thursday morning?",
                     "非常抱歉，这个季节比较忙。预约周四上午可以吗？"),
                line("A", "はい、お願いします……。",
                     "Yes, please...",
                     "好吧……"),
            ]),
            section("修理当日", "Repair day", "维修当天", "🔧", [
                line("C", "おはようございます。エアコンの修理に参りました。",
                     "Good morning. I'm here for the air conditioner repair.",
                     "早上好。来修空调的。"),
                line("A", "あ、お待ちしてました。こちらです。もう三日間エアコンなしで、やっと来てくれて嬉しいです。",
                     "Oh, I've been waiting. It's this way. Three days without AC — I'm so glad you're here.",
                     "啊，等着呢。在这边。三天没空调了，终于来了太高兴了。"),
                line("C", "この暑さじゃ大変でしたね。ちょっと見させてください。……ああ、基板が焼けてますね。",
                     "Must have been tough in this heat. Let me take a look. ...Ah, the circuit board is burnt.",
                     "这么热可真辛苦了。让我看看。……啊，主板烧了。"),
                line("A", "直りますか？",
                     "Can it be fixed?",
                     "能修好吗？"),
                line("C", "大丈夫ですよ。部品持ってきてますから、今日中に直ります。三十分くらいかかります。",
                     "No problem. I brought the parts, so it'll be fixed today. It'll take about thirty minutes.",
                     "没问题。零件带来了，今天就能修好。大概需要三十分钟。"),
                line("A", "よかった……。ちなみに、料金はいくらくらいですか？",
                     "Thank goodness... By the way, roughly how much will it cost?",
                     "太好了……对了，费用大概多少？"),
                line("C", "部品代と工賃で一万八千円くらいになります。",
                     "Parts and labor will be about 18,000 yen.",
                     "零件加工费大概一万八千日元。"),
            ]),
            section("修理完了", "Repair complete", "维修完成", "❄️", [
                line("C", "はい、終わりました。つけてみましょうか。",
                     "OK, all done. Shall we turn it on?",
                     "好，修完了。开一下看看？"),
                line("A", "お願いします。……おー、冷たい風が出てる！最高です！",
                     "Please. ...Oh, cold air is coming out! Amazing!",
                     "麻烦了。……哦，冷风出来了！太棒了！"),
                line("C", "よかったです。あと、フィルターもだいぶ汚れてたんで、きれいにしておきました。",
                     "Glad it works. Also, the filter was pretty dirty so I cleaned it.",
                     "太好了。另外过滤网也挺脏的，帮忙清理了。"),
                line("A", "え、ありがとうございます。全然掃除してなくて恥ずかしいんですけど……。",
                     "Oh, thank you. I'm embarrassed I hadn't cleaned it at all...",
                     "诶，谢谢。完全没打扫过不好意思……"),
                line("C", "年に一回は掃除した方がいいですよ。効きが全然違いますから。電気代も下がりますし。",
                     "You should clean it at least once a year. It makes a huge difference in performance. Your electricity bill drops too.",
                     "一年至少清洗一次比较好。效果完全不一样。电费也会降。"),
                line("A", "これからはちゃんとやります。今日は本当にありがとうございました。",
                     "I'll do it properly from now on. Thank you so much today.",
                     "以后一定好好做。今天真的谢谢了。"),
                line("C", "いえいえ。暑い日が続きますから、お体に気をつけてくださいね。",
                     "Not at all. The hot days are continuing, so please take care of yourself.",
                     "哪里。持续高温天气，请注意身体。"),
            ]),
        ],
    },
]


def main() -> None:
    path = ROOT / "public" / "data" / "ja_articles.json"
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    existing_ids = {item["id"] for item in data["items"]}

    added = 0
    for item in NEW_ITEMS:
        if item["id"] in existing_ids:
            print(f"  skip (exists): {item['id']}")
            continue

        if not item.get("titleRuby"):
            item["titleRuby"] = gr.make_ruby(item["titleWord"])
        item.setdefault("grammar", [])

        data["items"].append(item)
        added += 1
        print(f"  added: {item['id']}")

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"\nDone: added {added}, total {len(data['items'])} articles")


if __name__ == "__main__":
    main()
