#!/usr/bin/env python3
"""
batch5 → public/data/ja_articles.json

9 组新话题：
1 ゴミの分別 / 2 居酒屋送別会 / 3 レンタカー高速 / 4 温泉旅館
5 スマホ契約変更 / 6 銀行口座開設 / 7 花見の場所取り
8 年末大掃除 / 9 JLPT受験

运行: .venv/bin/python scripts/append_ja_articles_batch5.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import generate_ruby as gr  # noqa: E402


def full_reading(sentence: str) -> str:
    parts: list[str] = []
    for w in gr.tagger(sentence):
        k = w.feature.kana
        parts.append(gr.to_hira(k) if k else w.surface)
    return "".join(parts)


def enrich_segment(word: str, en: str, zh: str) -> dict:
    w = word.strip()
    return {
        "word": w,
        "jp": w,
        "en": en.strip(),
        "zh": zh.strip(),
        "reading": full_reading(w),
        "ruby": gr.make_ruby(w),
    }


def enrich_line(speaker: str, word: str, en: str, zh: str) -> dict:
    d = enrich_segment(word, en, zh)
    d["speaker"] = speaker
    return d


def section(
    heading: str,
    heading_en: str,
    heading_zh: str,
    badge: str,
    lines: list[tuple[str, str, str, str]],
) -> dict:
    return {
        "badge": badge,
        "headingWord": heading,
        "headingJp": heading,
        "headingEn": heading_en,
        "headingZh": heading_zh,
        "lines": [enrich_line(sp, w, e, z) for sp, w, e, z in lines],
    }


NEW_ITEMS: list[dict] = [

    # ===== 1. ゴミの分別 =====
    {
        "id": "n4-garbage-sorting-essay",
        "level": "N4–N3",
        "format": "essay",
        "titleWord": "ゴミの分別に苦戦する朝",
        "titleJp": "ゴミの分別に苦戦する朝",
        "titleEn": "A morning struggling with garbage sorting",
        "titleZh": "为垃圾分类苦恼的早晨",
        "titleRuby": [],
        "segments": [
            ("日本に来て最初に戸惑ったのは、ゴミの分別だった。",
             "The first thing that confused me when I came to Japan was garbage sorting.",
             "来日本后最先让我困惑的，就是垃圾分类。"),
            ("燃えるゴミ、燃えないゴミ、資源ゴミ。種類が多くて覚えられない。",
             "Burnable, non-burnable, recyclable — there are so many types I can't remember them.",
             "可燃垃圾、不可燃垃圾、资源垃圾，种类太多记不住。"),
            ("引っ越したばかりのころ、ペットボトルをそのまま出してしまった。",
             "Right after I moved in, I put out a plastic bottle without sorting it properly.",
             "刚搬来的时候，我直接把塑料瓶扔了出去。"),
            ("翌朝、ゴミ置き場に黄色いシールが貼られていた。",
             "The next morning, a yellow sticker had been put on my garbage at the collection point.",
             "第二天早上，垃圾放置处被贴了黄色标签。"),
            ("「分別不十分」と書いてあり、とても恥ずかしかった。",
             "It said 'insufficiently sorted' and I was really embarrassed.",
             "上面写着「分类不充分」，我非常尴尬。"),
            ("それから、冷蔵庫にゴミカレンダーを貼るようにした。",
             "After that, I started putting the garbage calendar on my fridge.",
             "从那以后，我把垃圾日历贴在了冰箱上。"),
            ("月曜と木曜は燃えるゴミ、水曜は資源ゴミ、金曜は燃えないゴミ。",
             "Monday and Thursday are burnable, Wednesday is recyclable, Friday is non-burnable.",
             "周一和周四是可燃垃圾，周三是资源垃圾，周五是不可燃垃圾。"),
            ("ペットボトルはキャップとラベルを外して、中を洗ってから出す。",
             "For plastic bottles, you remove the cap and label, rinse the inside, then put them out.",
             "塑料瓶要取下瓶盖和标签，洗干净里面再扔。"),
            ("最初は面倒だと思っていたが、今では習慣になった。",
             "At first I thought it was a hassle, but now it's become a habit.",
             "一开始觉得麻烦，但现在已经成了习惯。"),
            ("分別のルールは地域によって違うらしい。日本は奥が深い。",
             "Apparently the sorting rules differ by area. Japan really has a lot of depth.",
             "据说分类规则因地区而不同。日本真是深奥啊。"),
        ],
    },
    {
        "id": "n4-garbage-sorting-dialogue",
        "level": "N4–N3",
        "format": "dialogue",
        "titleWord": "管理人さんにゴミ出しルールを聞く",
        "titleJp": "管理人さんにゴミ出しルールを聞く",
        "titleEn": "Asking the building manager about garbage rules",
        "titleZh": "向管理员请教扔垃圾的规则",
        "titleRuby": [],
        "sections": [
            section("ゴミの出し方", "How to put out garbage", "扔垃圾的方法", "🗑️", [
                ("A", "すみません、ゴミの出し方がよく分からないのですが。",
                 "Excuse me, I'm not quite sure how to put out the garbage.",
                 "不好意思，我不太清楚怎么扔垃圾。"),
                ("B", "ああ、最初はみんな戸惑いますよね。何がわかりませんか？",
                 "Ah, everyone gets confused at first. What don't you understand?",
                 "啊，刚开始大家都会困惑的。有什么不明白的？"),
                ("A", "このプラスチックの容器は燃えるゴミですか？",
                 "Is this plastic container burnable garbage?",
                 "这个塑料容器是可燃垃圾吗？"),
                ("B", "いいえ、それは資源ゴミです。水曜日に出してくださいね。",
                 "No, that's recyclable. Please put it out on Wednesday.",
                 "不是，那是资源垃圾。请在周三扔。"),
            ]),
            section("回収日と時間", "Collection days and times", "回收日和时间", "📅", [
                ("A", "ゴミは何時までに出せばいいですか？",
                 "By what time should I put out the garbage?",
                 "垃圾要几点之前扔出去？"),
                ("B", "朝の八時までにお願いします。前の晩に出すのはやめてくださいね。",
                 "By 8 a.m., please. And please don't put it out the night before.",
                 "请在早上八点之前。前一天晚上不要扔哦。"),
                ("A", "わかりました。曜日ごとの一覧表はありますか？",
                 "Understood. Is there a schedule for each day of the week?",
                 "明白了。有按星期分的一览表吗？"),
                ("B", "はい、管理室にありますよ。一枚お渡ししますね。",
                 "Yes, we have them in the management office. I'll give you one.",
                 "有的，管理室里有。给您一份吧。"),
            ]),
        ],
    },

    # ===== 2. 居酒屋送別会 =====
    {
        "id": "n3-izakaya-farewell-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "居酒屋で送別会をした夜",
        "titleJp": "居酒屋で送別会をした夜",
        "titleEn": "The night we held a farewell party at an izakaya",
        "titleZh": "在居酒屋办送别会的那晚",
        "titleRuby": [],
        "segments": [
            ("同僚の田中さんが来月から大阪へ転勤になると聞いて、送別会を企画した。",
             "When I heard our colleague Tanaka was transferring to Osaka next month, I organized a farewell party.",
             "听说同事田中下个月要调去大阪，我就策划了一场送别会。"),
            ("駅前の居酒屋に、飲み放題付きのコースを予約した。",
             "I reserved an all-you-can-drink course at an izakaya in front of the station.",
             "在车站前的居酒屋预约了含畅饮的套餐。"),
            ("当日は十二人集まった。テーブルいっぱいに料理が並んだ。",
             "Twelve people showed up that day. The table was covered with dishes.",
             "当天来了十二个人。桌上摆满了菜。"),
            ("まずはビールで乾杯して、それぞれ思い出話を始めた。",
             "We started with a beer toast, and everyone began sharing memories.",
             "先用啤酒干杯，然后大家开始聊各自的回忆。"),
            ("田中さんは入社したときから面倒見がよく、よく相談に乗ってくれた。",
             "Tanaka had been caring ever since he joined the company, often giving advice.",
             "田中从入职起就很照顾人，经常帮忙出主意。"),
            ("「大阪でも頑張ってください」とみんなで色紙を渡した。",
             "We all handed him a signed card saying, 'Do your best in Osaka too.'",
             "大家一起递上写满祝福的色纸，说「在大阪也要加油」。"),
            ("田中さんは少し目を赤くして「ありがとう」と言った。",
             "Tanaka's eyes turned a little red as he said, 'Thank you.'",
             "田中眼眶微微泛红，说了声「谢谢」。"),
            ("帰り道、駅のホームで「また飲もうね」と約束した。",
             "On the way back, we promised each other on the station platform, 'Let's drink again sometime.'",
             "回去的路上，在站台上约好了「下次再一起喝」。"),
            ("送別会のあとは少し寂しいけれど、新しい出発を応援したいと思った。",
             "It felt a bit lonely after the farewell party, but I wanted to support his new start.",
             "送别会结束后虽然有些寂寞，但我想为他的新出发加油。"),
        ],
    },
    {
        "id": "n3-izakaya-farewell-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "居酒屋で予約と注文",
        "titleJp": "居酒屋で予約と注文",
        "titleEn": "Making a reservation and ordering at an izakaya",
        "titleZh": "在居酒屋预约和点菜",
        "titleRuby": [],
        "sections": [
            section("電話で予約", "Reserving by phone", "电话预约", "📞", [
                ("A", "お電話ありがとうございます。居酒屋さくらでございます。",
                 "Thank you for calling. This is Izakaya Sakura.",
                 "感谢来电。这里是居酒屋佐仓。"),
                ("B", "金曜日の夜、十二名で予約したいのですが。",
                 "I'd like to make a reservation for twelve people on Friday evening.",
                 "我想预约周五晚上，十二个人。"),
                ("A", "十二名様ですね。飲み放題付きのコースはいかがですか？",
                 "Twelve guests, I see. How about a course with all-you-can-drink?",
                 "十二位是吧。要不要含畅饮的套餐？"),
                ("B", "はい、お願いします。二時間コースでお願いします。",
                 "Yes, please. The two-hour course, please.",
                 "好的，麻烦了。请安排两小时的套餐。"),
            ]),
            section("当日の注文", "Ordering on the day", "当天点单", "🍺", [
                ("A", "最初のお飲み物はいかがなさいますか？",
                 "What would you like for your first drink?",
                 "第一杯要喝什么？"),
                ("B", "とりあえず生ビールを十二杯お願いします。",
                 "Twelve draft beers for now, please.",
                 "先来十二杯生啤。"),
                ("A", "かしこまりました。お料理はコースのほか、追加はございますか？",
                 "Certainly. Besides the course, would you like anything extra?",
                 "好的。除了套餐以外，还要加点什么吗？"),
                ("B", "枝豆と焼き鳥の盛り合わせを追加でお願いします。",
                 "We'd like to add edamame and a grilled chicken skewer platter.",
                 "请再加一份毛豆和烤鸡肉串拼盘。"),
            ]),
            section("お会計", "Paying the bill", "结账", "💰", [
                ("A", "お会計は幹事の方がまとめてお支払いですか？",
                 "Will the organizer pay for everyone together?",
                 "账单是由组织者统一付吗？"),
                ("B", "はい、まとめてカードでお願いします。",
                 "Yes, I'll pay it all together by card.",
                 "是的，一起刷卡。"),
            ]),
        ],
    },

    # ===== 3. レンタカー =====
    {
        "id": "n3-rental-car-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "レンタカーで初めて高速を走った日",
        "titleJp": "レンタカーで初めて高速を走った日",
        "titleEn": "The day I drove on the highway for the first time in a rental car",
        "titleZh": "第一次开租来的车上高速的那天",
        "titleRuby": [],
        "segments": [
            ("友人と箱根に行くことになり、レンタカーを借りた。",
             "My friend and I decided to go to Hakone, so we rented a car.",
             "和朋友决定去箱根，于是租了一辆车。"),
            ("店で免許証と保険の確認をして、鍵を受け取った。",
             "At the shop I confirmed my license and insurance, then received the keys.",
             "在店里确认了驾照和保险，拿到了钥匙。"),
            ("駐車場でナビを設定してから出発した。",
             "I set the navigation in the parking lot before departing.",
             "在停车场设好导航后出发了。"),
            ("高速に乗ったのは初めてで、合流するときは緊張した。",
             "It was my first time on the highway, and I was nervous merging.",
             "第一次上高速，汇入车流时非常紧张。"),
            ("料金所ではETCカードを使ったので、止まらずに通れた。",
             "I used an ETC card at the toll gate, so I could pass without stopping.",
             "收费站用了ETC卡，不用停车就过去了。"),
            ("サービスエリアで休憩して、コーヒーを飲んだ。",
             "I took a break at a service area and had some coffee.",
             "在服务区休息了一下，喝了杯咖啡。"),
            ("箱根に着いたのは二時間後だった。意外と近いと感じた。",
             "We arrived in Hakone two hours later. It felt surprisingly close.",
             "两个小时后到了箱根。感觉比想象中近。"),
            ("帰りはガソリンを満タンにして返却しなければならない。",
             "On the way back, I had to fill up the tank before returning the car.",
             "回程时必须加满油再还车。"),
            ("少し疲れたけれど、ドライブは楽しかった。また借りたいと思う。",
             "I was a bit tired, but the drive was fun. I'd like to rent one again.",
             "虽然有点累，但兜风很开心。还想再租。"),
        ],
    },
    {
        "id": "n3-rental-car-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "レンタカー店で手続き",
        "titleJp": "レンタカー店で手続き",
        "titleEn": "Processing paperwork at the rental car shop",
        "titleZh": "在租车店办手续",
        "titleRuby": [],
        "sections": [
            section("受付", "Reception", "接待", "🚗", [
                ("A", "ご予約の方ですか？お名前をお願いします。",
                 "Do you have a reservation? Your name, please.",
                 "您有预约吗？请告诉我您的名字。"),
                ("B", "はい、山田です。土曜から日曜の一泊二日で予約しました。",
                 "Yes, Yamada. I reserved for one night, Saturday to Sunday.",
                 "有的，山田。预约了周六到周日一晚两天。"),
                ("A", "免許証を拝見できますか？あと、保険のプランをご確認ください。",
                 "May I see your license? Also, please confirm the insurance plan.",
                 "可以看一下驾照吗？另外请确认一下保险方案。"),
                ("B", "はい、どうぞ。保険はフルカバーでお願いします。",
                 "Here you go. Full coverage insurance, please.",
                 "好的，给您。保险要全险的。"),
            ]),
            section("車の確認", "Checking the car", "确认车辆", "🔑", [
                ("A", "こちらがお車です。傷がないか一緒にご確認をお願いします。",
                 "Here's your car. Let's check together for any scratches.",
                 "这是您的车。请一起确认有没有划痕。"),
                ("B", "ここに小さな傷がありますね。",
                 "There's a small scratch here.",
                 "这里有一道小划痕。"),
                ("A", "はい、記録済みです。ガソリンは満タンでお返しくださいね。",
                 "Yes, that's already recorded. Please return it with a full tank.",
                 "是的，已经记录了。请加满油归还哦。"),
                ("B", "わかりました。ナビの使い方を教えてもらえますか？",
                 "Got it. Could you show me how to use the navigation?",
                 "明白了。能教我导航怎么用吗？"),
            ]),
        ],
    },

    # ===== 4. 温泉旅館 =====
    {
        "id": "n3-onsen-ryokan-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "温泉旅館で過ごす週末",
        "titleJp": "温泉旅館で過ごす週末",
        "titleEn": "A weekend spent at a hot spring inn",
        "titleZh": "在温泉旅馆度过的周末",
        "titleRuby": [],
        "segments": [
            ("仕事の疲れがたまっていたので、週末に温泉旅館を予約した。",
             "I'd been piling up work fatigue, so I booked a hot spring inn for the weekend.",
             "工作的疲劳积累了不少，于是预约了周末的温泉旅馆。"),
            ("チェックインのとき、仲居さんが部屋まで案内してくれた。",
             "At check-in, a room attendant guided me to my room.",
             "办入住时，服务员带我到了房间。"),
            ("部屋には畳が敷いてあって、窓から山が見えた。",
             "The room had tatami mats, and I could see mountains from the window.",
             "房间里铺着榻榻米，从窗户能看到山。"),
            ("浴衣に着替えて、まず露天風呂に入った。",
             "I changed into a yukata and went to the outdoor bath first.",
             "换上浴衣，先去泡了露天温泉。"),
            ("湯加減がちょうどよくて、体の力が抜けていくのを感じた。",
             "The water temperature was just right, and I felt the tension leaving my body.",
             "水温刚刚好，感觉身体的疲惫都在慢慢消散。"),
            ("夕食は部屋食で、刺身や天ぷらが出てきた。",
             "Dinner was served in the room — sashimi, tempura, and more.",
             "晚餐是在房间里吃的，上了刺身和天妇罗。"),
            ("食後にもう一度お風呂に入って、布団でぐっすり眠った。",
             "After dinner I took another bath, then slept soundly in the futon.",
             "饭后又泡了一次澡，在被褥里睡得很沉。"),
            ("翌朝、朝食のあとにチェックアウトした。",
             "The next morning, I checked out after breakfast.",
             "第二天早上，吃完早饭后退了房。"),
            ("帰るころにはすっかりリフレッシュしていた。また来たい。",
             "By the time I headed back, I felt completely refreshed. I want to come again.",
             "到回去的时候已经完全恢复精神了。还想再来。"),
        ],
    },
    {
        "id": "n3-onsen-ryokan-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "旅館のフロントで",
        "titleJp": "旅館のフロントで",
        "titleEn": "At the ryokan front desk",
        "titleZh": "在旅馆前台",
        "titleRuby": [],
        "sections": [
            section("チェックイン", "Check-in", "办入住", "♨️", [
                ("A", "いらっしゃいませ。ご予約のお名前をお願いいたします。",
                 "Welcome. May I have the name on your reservation?",
                 "欢迎光临。请告诉我预约的姓名。"),
                ("B", "鈴木です。一泊二食付きで予約しました。",
                 "Suzuki. I reserved with dinner and breakfast included.",
                 "铃木。预约的是一晚含两餐的。"),
                ("A", "お部屋は二階の和室でございます。浴衣はこちらからお選びください。",
                 "Your room is a Japanese-style room on the second floor. Please choose a yukata from here.",
                 "房间是二楼的和式房间。浴衣请从这里选。"),
                ("B", "ありがとうございます。お風呂は何時まで入れますか？",
                 "Thank you. Until what time can I use the bath?",
                 "谢谢。温泉可以泡到几点？"),
            ]),
            section("温泉について", "About the hot spring", "关于温泉", "🧖", [
                ("A", "大浴場は夜の十一時まで、朝は六時からご利用いただけます。",
                 "The large bath is available until 11 p.m., and from 6 a.m. in the morning.",
                 "大浴场到晚上十一点，早上六点开始可以使用。"),
                ("B", "露天風呂もありますか？",
                 "Is there an outdoor bath too?",
                 "有露天温泉吗？"),
                ("A", "はい、大浴場の奥にございます。タオルはお部屋のものをお持ちください。",
                 "Yes, it's in the back of the large bath. Please bring the towels from your room.",
                 "有的，在大浴场的里面。请带房间里的毛巾。"),
                ("B", "わかりました。夕食は何時からですか？",
                 "Got it. What time is dinner?",
                 "明白了。晚饭几点开始？"),
                ("A", "六時半からお部屋にお持ちします。",
                 "We'll bring it to your room from 6:30.",
                 "六点半开始送到房间。"),
            ]),
        ],
    },

    # ===== 5. スマホ契約変更 =====
    {
        "id": "n3-phone-contract-essay",
        "level": "N3–N2",
        "format": "essay",
        "titleWord": "スマホの契約を変更しに行った日",
        "titleJp": "スマホの契約を変更しに行った日",
        "titleEn": "The day I went to change my phone contract",
        "titleZh": "去换手机套餐的那天",
        "titleRuby": [],
        "segments": [
            ("毎月のスマホ代が高いと感じていたので、契約を見直すことにした。",
             "I felt my monthly phone bill was too high, so I decided to review my contract.",
             "觉得每个月的手机费太贵了，于是决定重新审视一下合同。"),
            ("近くの携帯ショップに行って、番号札を取った。",
             "I went to the nearby phone shop and took a number ticket.",
             "去了附近的手机店，取了号码牌。"),
            ("三十分ほど待って、ようやく順番が来た。",
             "I waited about thirty minutes before my turn finally came.",
             "等了大约三十分钟，终于轮到我了。"),
            ("今のプランは通話し放題で月八千円だが、通話はほとんどしない。",
             "My current plan is unlimited calls for 8,000 yen a month, but I hardly make calls.",
             "现在的套餐是不限通话每月八千日元，但我几乎不打电话。"),
            ("店員さんがデータ量と通話の使い方を確認してくれた。",
             "The staff member checked my data usage and calling habits.",
             "店员帮我确认了流量使用量和通话情况。"),
            ("月五千円のプランに変更すれば、年間で三万六千円も節約できるらしい。",
             "Apparently, switching to a 5,000 yen plan would save me 36,000 yen a year.",
             "据说换成五千日元的套餐，一年能省三万六千日元。"),
            ("手続きは二十分ほどで終わった。身分証とクレジットカードが必要だった。",
             "The process took about twenty minutes. I needed my ID and credit card.",
             "手续大约二十分钟办完了。需要身份证和信用卡。"),
            ("新しいプランは来月から適用されるとのことだった。",
             "I was told the new plan would take effect starting next month.",
             "新套餐从下个月开始生效。"),
            ("もっと早く見直せばよかったと少し後悔した。",
             "I regretted a little that I hadn't reviewed it sooner.",
             "有点后悔没有早点去改。"),
        ],
    },
    {
        "id": "n3-phone-contract-dialogue",
        "level": "N3–N2",
        "format": "dialogue",
        "titleWord": "携帯ショップでプラン変更",
        "titleJp": "携帯ショップでプラン変更",
        "titleEn": "Changing plans at the phone shop",
        "titleZh": "在手机店换套餐",
        "titleRuby": [],
        "sections": [
            section("現在のプラン確認", "Checking the current plan", "确认现有套餐", "📱", [
                ("A", "本日はどのようなご用件でしょうか。",
                 "How may I help you today?",
                 "今天有什么需要帮忙的？"),
                ("B", "料金プランを安いものに変えたいのですが。",
                 "I'd like to switch to a cheaper plan.",
                 "我想换个便宜点的套餐。"),
                ("A", "現在のプランを確認しますね。月々八千円の通話し放題プランですね。",
                 "Let me check your current plan. It's the 8,000 yen unlimited calls plan, right?",
                 "我确认一下现在的套餐。是每月八千日元的通话无限套餐对吧。"),
                ("B", "はい。でも電話はほとんど使わないんです。",
                 "Yes. But I hardly use the phone function.",
                 "对。但我几乎不打电话。"),
            ]),
            section("新プランの提案", "New plan suggestion", "新套餐建议", "💡", [
                ("A", "データ二十ギガで通話は従量制のプランなら月五千円です。",
                 "A plan with 20 GB data and pay-per-call would be 5,000 yen a month.",
                 "二十GB流量加按量计费通话的套餐是每月五千日元。"),
                ("B", "それだとデータは足りますか？",
                 "Would that be enough data?",
                 "那流量够用吗？"),
                ("A", "先月のご利用は十五ギガでしたので、十分だと思います。",
                 "Last month you used 15 GB, so it should be plenty.",
                 "上个月您用了十五GB，应该够的。"),
                ("B", "では、そのプランにしてください。",
                 "Then please switch me to that plan.",
                 "那就换成那个套餐吧。"),
            ]),
            section("手続き", "Processing", "办手续", "📝", [
                ("A", "ご本人確認のため、身分証をお願いできますか。",
                 "For identity verification, may I see your ID?",
                 "为了验证身份，能出示一下证件吗？"),
                ("B", "在留カードでいいですか？",
                 "Is a residence card OK?",
                 "在留卡可以吗？"),
                ("A", "はい、大丈夫です。新しいプランは来月一日から適用になります。",
                 "Yes, that's fine. The new plan will take effect from the first of next month.",
                 "可以的。新套餐从下个月一号开始生效。"),
            ]),
        ],
    },

    # ===== 6. 銀行口座開設 =====
    {
        "id": "n3-bank-account-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "銀行で口座を開設した日",
        "titleJp": "銀行で口座を開設した日",
        "titleEn": "The day I opened a bank account",
        "titleZh": "在银行开户的那天",
        "titleRuby": [],
        "segments": [
            ("日本で生活するために、銀行口座が必要になった。",
             "I needed a bank account to live in Japan.",
             "为了在日本生活，需要开一个银行账户。"),
            ("学校の近くにある銀行へ、在留カードと印鑑を持って行った。",
             "I went to the bank near my school with my residence card and personal seal.",
             "带着在留卡和印章去了学校附近的银行。"),
            ("窓口で「口座を開きたい」と伝えると、申込書を渡された。",
             "When I told the counter I wanted to open an account, they handed me an application form.",
             "在窗口说想开户后，递给了我申请表。"),
            ("名前、住所、電話番号を記入して、印鑑を押した。",
             "I filled in my name, address, and phone number, then stamped my seal.",
             "填了姓名、地址、电话号码，盖了印章。"),
            ("窓口の人が丁寧に説明してくれたので、安心だった。",
             "The person at the counter explained things carefully, so I felt at ease.",
             "窗口的人耐心地给我讲解，让我很安心。"),
            ("キャッシュカードは一週間ほどで届くと言われた。",
             "I was told the cash card would arrive in about a week.",
             "说银行卡大约一周后寄到。"),
            ("通帳はその場でもらえた。最初の残高はゼロ円だ。",
             "I received the passbook on the spot. The initial balance was zero yen.",
             "存折当场就拿到了。初始余额是零日元。"),
            ("帰りにATMで一万円を入金した。これで家賃の振り込みもできる。",
             "On the way home, I deposited 10,000 yen at the ATM. Now I can transfer my rent too.",
             "回去时在ATM存了一万日元。这下房租也能转账了。"),
            ("口座ができたことで、日本での生活が本格的に始まった気がした。",
             "Having an account made me feel like my life in Japan had truly begun.",
             "开了户之后，感觉在日本的生活才真正开始了。"),
        ],
    },
    {
        "id": "n3-bank-account-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "銀行の窓口で口座開設",
        "titleJp": "銀行の窓口で口座開設",
        "titleEn": "Opening an account at the bank counter",
        "titleZh": "在银行窗口开户",
        "titleRuby": [],
        "sections": [
            section("受付", "Reception", "接待", "🏦", [
                ("A", "いらっしゃいませ。本日はどのようなご用件ですか。",
                 "Welcome. How may I help you today?",
                 "欢迎光临。今天有什么需要？"),
                ("B", "普通預金の口座を開設したいのですが。",
                 "I'd like to open a regular savings account.",
                 "我想开一个普通储蓄账户。"),
                ("A", "かしこまりました。ご本人確認のため、身分証をお見せいただけますか。",
                 "Certainly. For verification, could you show me your ID?",
                 "好的。为了确认身份，能出示一下证件吗？"),
                ("B", "在留カードとパスポートを持ってきました。",
                 "I brought my residence card and passport.",
                 "我带了在留卡和护照。"),
            ]),
            section("申込書の記入", "Filling out the form", "填写申请表", "✍️", [
                ("A", "こちらの申込書に、お名前とご住所をご記入ください。",
                 "Please fill in your name and address on this application form.",
                 "请在这张申请表上填写您的姓名和地址。"),
                ("B", "印鑑はここに押せばいいですか？",
                 "Should I stamp my seal here?",
                 "印章盖在这里就行吗？"),
                ("A", "はい、そこでお願いします。暗証番号は四桁で設定してください。",
                 "Yes, right there, please. Please set a four-digit PIN.",
                 "对，盖在那里。请设置四位数密码。"),
                ("B", "カードはいつ届きますか？",
                 "When will the card arrive?",
                 "银行卡什么时候到？"),
                ("A", "一週間ほどでご登録のご住所にお届けします。通帳は本日お渡しします。",
                 "It will be delivered to your registered address in about a week. You'll receive the passbook today.",
                 "大约一周后会寄到您登记的地址。存折今天给您。"),
            ]),
        ],
    },

    # ===== 7. 花見の場所取り =====
    {
        "id": "n3-hanami-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "花見の場所取りを任された日",
        "titleJp": "花見の場所取りを任された日",
        "titleEn": "The day I was put in charge of saving a spot for hanami",
        "titleZh": "被安排去占赏花位的那天",
        "titleRuby": [],
        "segments": [
            ("会社の花見で、場所取り係に指名された。",
             "I was appointed as the spot-saver for the company hanami.",
             "在公司的赏花活动中，我被指定为占位负责人。"),
            ("朝の八時に公園に着いたが、もう何組かシートを敷いていた。",
             "I arrived at the park at 8 a.m., but several groups had already laid out sheets.",
             "早上八点到了公园，但已经有好几组人铺好了垫子。"),
            ("桜の木の下の良い場所を見つけて、ブルーシートを広げた。",
             "I found a nice spot under a cherry tree and spread out a blue tarp.",
             "找到了一个樱花树下的好位子，铺开了蓝色防水布。"),
            ("風が強くて、シートの四隅に荷物を置いて押さえた。",
             "The wind was strong, so I placed bags on the four corners to hold it down.",
             "风很大，在垫子四个角放了行李压住。"),
            ("みんなが来るまで三時間ほど一人で待った。",
             "I waited alone for about three hours until everyone arrived.",
             "大家来之前，我一个人等了大约三个小时。"),
            ("隣のグループの人が「お花見ですか？いい場所ですね」と話しかけてきた。",
             "A person from the next group over said to me, 'Hanami? Nice spot you've got.'",
             "旁边那组的人跟我搭话说「赏花吗？位置真不错啊」。"),
            ("昼すぎにみんなが到着して、お弁当とお酒で盛り上がった。",
             "Everyone arrived past noon, and we had a great time with bento and drinks.",
             "过了中午大家到齐了，边吃便当边喝酒，气氛很热烈。"),
            ("満開の桜の下で食べるおにぎりは格別だった。",
             "Rice balls eaten under cherry blossoms in full bloom were exceptional.",
             "在盛开的樱花下吃饭团，格外美味。"),
            ("帰りにゴミを全部持ち帰った。来年もこの場所がいい。",
             "We took all the trash home with us on the way back. I hope we get this spot next year too.",
             "回去时把垃圾全部带走了。明年也想占到这个位子。"),
        ],
    },
    {
        "id": "n3-hanami-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "公園で花見の場所を確保する",
        "titleJp": "公園で花見の場所を確保する",
        "titleEn": "Securing a hanami spot at the park",
        "titleZh": "在公园占赏花位",
        "titleRuby": [],
        "sections": [
            section("場所を探す", "Finding a spot", "找位子", "🌸", [
                ("A", "すみません、この辺はもう空いていないですよね。",
                 "Excuse me, there's no space left around here, is there?",
                 "不好意思，这附近已经没有空位了吧。"),
                ("B", "あの木の向こうならまだ空いてますよ。",
                 "There's still space beyond that tree over there.",
                 "那棵树后面还有空位哦。"),
                ("A", "ほんとですか。ありがとうございます！",
                 "Really? Thank you so much!",
                 "真的吗？太感谢了！"),
                ("B", "うちは十二時くらいに帰るので、そのあとここも使えますよ。",
                 "We're leaving around noon, so you can use this spot after that too.",
                 "我们大概十二点走，之后这里也可以用。"),
            ]),
            section("仲間と合流", "Meeting up with friends", "和同伴汇合", "🍱", [
                ("A", "みんな遅いね。連絡してみようか。",
                 "Everyone's late. Should I try contacting them?",
                 "大家都迟到了啊。要不联系一下？"),
                ("B", "さっきメッセージ来たよ。もうすぐ着くって。",
                 "I just got a message. They said they're almost here.",
                 "刚收到消息了。说马上到。"),
                ("A", "お弁当とビールは買ってきてくれるかな。",
                 "I wonder if they're bringing bento and beer.",
                 "不知道他们有没有买便当和啤酒。"),
                ("B", "大丈夫、幹事の中村さんが手配してるはずだよ。",
                 "Don't worry, Nakamura the organizer should have arranged it.",
                 "没事，组织者中村应该已经安排好了。"),
            ]),
        ],
    },

    # ===== 8. 年末大掃除 =====
    {
        "id": "n3-yearend-essay",
        "level": "N3",
        "format": "essay",
        "titleWord": "年末の大掃除と年越しそば",
        "titleJp": "年末の大掃除と年越しそば",
        "titleEn": "Year-end cleaning and New Year's Eve soba",
        "titleZh": "年末大扫除和跨年荞麦面",
        "titleRuby": [],
        "segments": [
            ("十二月三十日、一年の汚れを落とすために大掃除を始めた。",
             "On December 30th, I started the big cleaning to wash away a year's worth of grime.",
             "十二月三十号，为了除去一年的污垢，开始了大扫除。"),
            ("まずキッチンの換気扇を外して、油汚れを洗った。",
             "First I took off the kitchen ventilation fan and washed off the grease.",
             "先把厨房的换气扇拆下来，清洗了油污。"),
            ("窓ガラスを拭いて、カーテンも洗濯機に入れた。",
             "I wiped the window glass and put the curtains in the washing machine.",
             "擦了窗玻璃，窗帘也放进了洗衣机。"),
            ("普段やらない場所を掃除すると、こんなに汚れていたのかと驚く。",
             "When you clean places you normally don't, you're surprised at how dirty they were.",
             "打扫平时不清理的地方时，才惊讶原来这么脏。"),
            ("午後には友人が手伝いに来てくれた。二人だと早い。",
             "In the afternoon a friend came to help. With two people it goes faster.",
             "下午朋友来帮忙了。两个人干起来快多了。"),
            ("夕方にはすっかりきれいになった。気持ちも新しくなった。",
             "By evening everything was spotless. My spirits felt renewed too.",
             "到傍晚已经打扫得干干净净。心情也焕然一新。"),
            ("夜は年越しそばを作って食べた。細く長く生きられるようにという願いを込めて。",
             "At night I made and ate New Year's Eve soba, with the wish to live a long, thin life.",
             "晚上做了跨年荞麦面来吃，寄托着细水长流的愿望。"),
            ("除夜の鐘をテレビで見ながら、今年一年を振り返った。",
             "While watching the New Year's Eve bell on TV, I reflected on the past year.",
             "一边看电视上的除夕钟声，一边回顾了这一年。"),
            ("来年はもっといい年にしたいと思いながら、新年を迎えた。",
             "I welcomed the new year hoping it would be even better than this one.",
             "怀着明年会更好的心愿，迎来了新年。"),
        ],
    },
    {
        "id": "n3-yearend-dialogue",
        "level": "N3",
        "format": "dialogue",
        "titleWord": "年末、友人と電話で",
        "titleJp": "年末、友人と電話で",
        "titleEn": "A year-end phone call with a friend",
        "titleZh": "年末和朋友打电话",
        "titleRuby": [],
        "sections": [
            section("大掃除の話", "Talking about cleaning", "聊大扫除", "🧹", [
                ("A", "もう大掃除した？",
                 "Have you done the big cleaning yet?",
                 "你大扫除做了吗？"),
                ("B", "まだ半分しか終わってない。換気扇が大変だった。",
                 "I've only finished half. The ventilation fan was tough.",
                 "才做了一半。换气扇搞得累死了。"),
                ("A", "わかる。うちもキッチンに一番時間がかかったよ。",
                 "I know what you mean. Our kitchen took the longest too.",
                 "懂的。我家也是厨房花的时间最多。"),
                ("B", "明日中には終わらせたいんだけどね。",
                 "I'd like to finish it by the end of tomorrow though.",
                 "想在明天之内搞完。"),
            ]),
            section("年越しの予定", "New Year's Eve plans", "跨年安排", "🎍", [
                ("A", "年越しそば、今年はどうする？",
                 "What are you doing about New Year's Eve soba this year?",
                 "今年跨年荞麦面怎么办？"),
                ("B", "自分で作ろうかなと思ってる。天ぷらも揚げたい。",
                 "I'm thinking of making it myself. I want to fry tempura too.",
                 "想自己做。还想炸天妇罗。"),
                ("A", "いいね。うちはテレビで紅白を見ながら食べる予定。",
                 "Nice. We plan to eat while watching Kohaku on TV.",
                 "不错。我打算一边看红白歌会一边吃。"),
                ("B", "じゃあ、年が明けたらまた連絡するね。よいお年を。",
                 "OK, I'll get in touch again after the new year. Have a good one.",
                 "那新年到了再联系。祝你新年快乐。"),
                ("A", "よいお年を！来年もよろしくね。",
                 "Happy New Year! Looking forward to next year too.",
                 "新年快乐！明年也请多关照。"),
            ]),
        ],
    },

    # ===== 9. JLPT受験 =====
    {
        "id": "n3-jlpt-essay",
        "level": "N3–N2",
        "format": "essay",
        "titleWord": "日本語能力試験を受けた日",
        "titleJp": "日本語能力試験を受けた日",
        "titleEn": "The day I took the JLPT",
        "titleZh": "参加日语能力考试的那天",
        "titleRuby": [],
        "segments": [
            ("半年間勉強して、いよいよ日本語能力試験の日が来た。",
             "After six months of study, the day of the JLPT had finally arrived.",
             "学了半年，日语能力考试的日子终于到了。"),
            ("試験会場は大学のキャンパスで、受験者でいっぱいだった。",
             "The test venue was a university campus, packed with examinees.",
             "考场在大学校园里，到处都是考生。"),
            ("受験票と身分証を確認されて、教室に入った。",
             "After my admission ticket and ID were checked, I entered the classroom.",
             "确认了准考证和身份证后，进了教室。"),
            ("最初は文字・語彙のセクションで、漢字の読み方が出た。",
             "First was the characters and vocabulary section, testing kanji readings.",
             "第一部分是文字·词汇，考了汉字读法。"),
            ("文法のセクションでは、似た表現の使い分けが難しかった。",
             "In the grammar section, distinguishing between similar expressions was difficult.",
             "语法部分里，区分相似表达很难。"),
            ("読解は時間が足りなくて、最後の問題は急いで解いた。",
             "I ran out of time on reading comprehension and rushed through the last question.",
             "阅读理解时间不够，最后一题赶着做完的。"),
            ("聴解は普段からポッドキャストを聞いていたおかげで、わりと聞き取れた。",
             "Thanks to listening to podcasts regularly, I could follow the listening section fairly well.",
             "多亏平时听播客，听力部分还算听得懂。"),
            ("試験が終わったあと、会場の外で友人と答え合わせをした。",
             "After the exam, I compared answers with a friend outside the venue.",
             "考完后在考场外和朋友对了答案。"),
            ("合格発表は二ヶ月後だ。受かっていますように。",
             "Results come out in two months. I hope I passed.",
             "合格发表在两个月后。希望能考过。"),
        ],
    },
    {
        "id": "n3-jlpt-dialogue",
        "level": "N3–N2",
        "format": "dialogue",
        "titleWord": "試験会場で隣の受験者と",
        "titleJp": "試験会場で隣の受験者と",
        "titleEn": "Chatting with the person next to me at the exam venue",
        "titleZh": "在考场和旁边的考生聊天",
        "titleRuby": [],
        "sections": [
            section("試験前", "Before the exam", "考试前", "📝", [
                ("A", "今日はN2ですか？",
                 "Are you taking N2 today?",
                 "你今天考N2吗？"),
                ("B", "はい。すごく緊張してます。どのくらい勉強しましたか？",
                 "Yes. I'm super nervous. How long did you study?",
                 "对。特别紧张。你学了多久？"),
                ("A", "半年くらいです。聴解が苦手で心配です。",
                 "About half a year. I'm worried because listening is my weak point.",
                 "大约半年。听力不太行，很担心。"),
                ("B", "僕は読解の時間配分がいつもうまくいかないんです。",
                 "For me, I can never manage my time well on reading comprehension.",
                 "我是阅读理解的时间分配总是搞不好。"),
            ]),
            section("試験後", "After the exam", "考试后", "😮‍💨", [
                ("A", "おつかれさま。どうだった？",
                 "Good work. How was it?",
                 "辛苦了。考得怎么样？"),
                ("B", "文法は思ったより難しかった。あの敬語の問題、わかりましたか？",
                 "Grammar was harder than I expected. Did you get that keigo question?",
                 "语法比想象中难。那道敬语的题你做出来了吗？"),
                ("A", "あれは迷いました。読解は最後の長文が大変だった。",
                 "That one I wasn't sure about. The last long passage in reading was tough.",
                 "那题我也犹豫了。阅读最后一篇长文好难。"),
                ("B", "結果は二ヶ月後ですよね。受かってるといいですね。",
                 "Results are in two months, right? I hope we both pass.",
                 "成绩两个月后出对吧。希望都能过。"),
                ("A", "お互い受かりますように！おつかれさまでした。",
                 "May we both pass! Great job today.",
                 "祝我们都能过！辛苦了。"),
            ]),
        ],
    },
]


def main():
    path = ROOT / "public" / "data" / "ja_articles.json"
    data = json.loads(path.read_text("utf-8"))
    existing_ids = {it["id"] for it in data["items"]}

    added = 0
    for item in NEW_ITEMS:
        if item["id"] in existing_ids:
            print(f"  skip (exists): {item['id']}")
            continue

        # enrich segments
        if item["format"] == "essay":
            raw = item["segments"]
            item["segments"] = [enrich_segment(w, e, z) for w, e, z in raw]

        # enrich titleRuby
        item["titleRuby"] = gr.make_ruby(item["titleWord"])

        data["items"].append(item)
        added += 1
        print(f"  added: {item['id']} — {item['titleWord']}")

    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", "utf-8")
    print(f"\n合計 {added} 件追加しました。")


if __name__ == "__main__":
    main()
