#!/usr/bin/env python3
"""
batch6 → public/data/ja_articles.json

9 组 N2 长文话题：
1 コンビニ文化 / 2 空気を読む / 3 都会と地方 / 4 一人暮らし
5 外国人として働く / 6 趣味が仕事に / 7 キャッシュレス
8 テレワーク / 9 少子化

运行: python3 scripts/append_ja_articles_batch6.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import generate_ruby as gr  # noqa: E402


def full_reading(sentence: str) -> str:
    parts: list[str] = []
    for w in gr.tagger(sentence):
        k = w.feature.kana
        parts.append(gr.to_hira(k) if k else w.surface)
    return "".join(parts)


def enrich_segment(word: str, en: str, zh: str) -> dict:
    w = word.strip()
    return {
        "word": w,
        "jp": w,
        "en": en.strip(),
        "zh": zh.strip(),
        "reading": full_reading(w),
        "ruby": gr.make_ruby(w),
    }


def enrich_line(speaker: str, word: str, en: str, zh: str) -> dict:
    d = enrich_segment(word, en, zh)
    d["speaker"] = speaker
    return d


def section(
    heading: str,
    heading_en: str,
    heading_zh: str,
    badge: str,
    lines: list[tuple[str, str, str, str]],
) -> dict:
    return {
        "badge": badge,
        "headingWord": heading,
        "headingJp": heading,
        "headingEn": heading_en,
        "headingZh": heading_zh,
        "lines": [enrich_line(sp, w, e, z) for sp, w, e, z in lines],
    }


NEW_ITEMS: list[dict] = [

    # ===== 1. コンビニ文化 =====
    {
        "id": "n2-conbini-culture-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "日本のコンビニ文化について",
        "titleJp": "日本のコンビニ文化について",
        "titleEn": "On Japan's convenience store culture",
        "titleZh": "关于日本的便利店文化",
        "titleRuby": [],
        "segments": [
            ("日本には約五万六千店のコンビニがあり、都市部ではどこを歩いても五分以内に見つかると言われている。",
             "There are about 56,000 convenience stores in Japan, and in urban areas it's said you can find one within a five-minute walk no matter where you are.",
             "日本大约有五万六千家便利店，据说在城市里无论走到哪里，五分钟内都能找到一家。"),
            ("コンビニが日本に初めて登場したのは一九七四年のことで、以来、その存在は人々の暮らしに深く根づいた。",
             "Convenience stores first appeared in Japan in 1974, and since then they have become deeply rooted in people's lives.",
             "便利店最早出现在日本是1974年，此后它的存在深深扎根于人们的生活中。"),
            ("食品だけでなく、公共料金の支払い、荷物の受け取り、チケットの発券まで、あらゆるサービスが一か所で完結する。",
             "Not just food — paying utility bills, picking up packages, issuing tickets — all kinds of services are completed in one place.",
             "不仅是食品，缴纳公共事业费、领取包裹、出票等各种服务都能在一处搞定。"),
            ("おにぎりや弁当の品質は年々進化しており、専門店と遜色ないという声も少なくない。",
             "The quality of rice balls and bento has been evolving year after year, and many say they're on par with specialty shops.",
             "饭团和便当的品质逐年进化，不少人说和专卖店不相上下。"),
            ("二十四時間営業であることも大きな特徴だが、近年は人手不足を理由に深夜営業を縮小する動きもある。",
             "Being open 24 hours is a major feature, but in recent years there's a trend to reduce late-night hours due to labor shortages.",
             "二十四小时营业也是一大特征，不过近年来因为人手不足，也有缩减深夜营业的趋势。"),
            ("外国人観光客にとってもコンビニは便利な存在で、ATMや無料Wi-Fiが利用できる点が特に好評だ。",
             "Convenience stores are also useful for foreign tourists, with ATMs and free Wi-Fi being especially well-received.",
             "对外国游客来说便利店也很方便，能使用ATM和免费WiFi这一点尤其受好评。"),
            ("一方で、コンビニの普及により、個人経営の商店が減少したという批判もある。",
             "On the other hand, there is also criticism that the spread of convenience stores has led to a decline in independently run shops.",
             "另一方面，也有人批评便利店的普及导致了个人经营的商店减少。"),
            ("さらに、フランチャイズのオーナーが過酷な労働環境に置かれている問題も指摘されている。",
             "Furthermore, the issue of franchise owners being placed in harsh working conditions has also been pointed out.",
             "此外，加盟店主被置于严苛劳动环境中的问题也被指出。"),
            ("食品ロスの問題にも目を向ける必要がある。売れ残った弁当やパンが毎日大量に廃棄されているのだ。",
             "We also need to pay attention to the food waste problem. Unsold bento and bread are discarded in large quantities every day.",
             "食物浪费的问题也需要关注。卖不完的便当和面包每天都被大量丢弃。"),
            ("こうした課題はあるものの、コンビニは日本社会を支えるインフラの一つであり続けるだろう。",
             "Despite these issues, convenience stores will likely continue to be one of the pieces of infrastructure that support Japanese society.",
             "尽管有这些课题，便利店仍将作为支撑日本社会的基础设施之一存在下去。"),
            ("災害時には物資の供給拠点にもなるなど、その社会的役割は今後さらに広がる可能性がある。",
             "During disasters they even serve as supply hubs, and their social role may expand even further in the future.",
             "灾害时还能成为物资供给据点，其社会作用今后有可能进一步扩大。"),
            ("私たちはコンビニの便利さを享受する一方で、その裏にある問題にも目を向けるべきではないだろうか。",
             "While we enjoy the convenience of konbini, shouldn't we also pay attention to the problems behind them?",
             "我们在享受便利店便利的同时，是不是也应该关注其背后的问题呢？"),
        ],
    },
    {
        "id": "n2-conbini-culture-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "コンビニの便利さと問題点について話す",
        "titleJp": "コンビニの便利さと問題点について話す",
        "titleEn": "Discussing the convenience and issues of konbini",
        "titleZh": "聊便利店的便利与问题",
        "titleRuby": [],
        "sections": [
            section("便利さについて", "About convenience", "关于便利性", "🏪", [
                ("A", "日本に来て一番驚いたのは、コンビニがどこにでもあることだったな。",
                 "The thing that surprised me most when I came to Japan was that there are convenience stores everywhere.",
                 "来日本后最让我惊讶的是到处都有便利店。"),
                ("B", "確かに。しかも二十四時間やっているから、生活のリズムに関係なく使えるよね。",
                 "True. And since they're open 24 hours, you can use them regardless of your schedule.",
                 "确实。而且二十四小时营业，不管什么作息都能用。"),
                ("A", "公共料金の支払いまでできるって知ったときは本当に感動した。",
                 "I was genuinely impressed when I learned you could even pay utility bills there.",
                 "知道连公共事业费都能交的时候真的感动了。"),
                ("B", "最近はセルフレジも増えて、日本語に自信がなくても買い物しやすくなったと思う。",
                 "Recently self-checkout registers have increased, making it easier to shop even if you're not confident in Japanese.",
                 "最近自助收银台也多了，即使日语不太好也容易购物了。"),
            ]),
            section("問題点について", "About the issues", "关于问题", "🤔", [
                ("A", "ただ、コンビニのせいで個人商店が減ったっていう話も聞くよね。",
                 "But you also hear that independently owned shops have declined because of convenience stores.",
                 "不过也听说因为便利店，个人商店减少了。"),
                ("B", "それは確かにある。うちの近所にあった八百屋さんも去年閉店してしまった。",
                 "That's definitely true. The greengrocer near my place also closed last year.",
                 "这确实有。我家附近的蔬菜店去年也关门了。"),
                ("A", "食品ロスの問題も深刻だと思う。毎日どれだけ捨てられているんだろう。",
                 "I think the food waste issue is serious too. I wonder how much is thrown away every day.",
                 "食物浪费的问题我也觉得很严重。每天到底扔了多少啊。"),
                ("B", "最近は値引きシールを貼って廃棄を減らす取り組みも始まっているみたいだけどね。",
                 "It seems like they've started efforts to reduce waste by putting discount stickers on items recently.",
                 "最近好像也开始贴打折标签来减少丢弃的做法了。"),
                ("A", "便利さと社会的コストのバランスって、簡単には答えが出ないよね。",
                 "The balance between convenience and social cost — it's not easy to find an answer, is it?",
                 "便利性和社会成本的平衡，确实不容易得出答案呢。"),
            ]),
        ],
    },

    # ===== 2. 空気を読む =====
    {
        "id": "n2-kuuki-yomu-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "「空気を読む」ということ",
        "titleJp": "「空気を読む」ということ",
        "titleEn": "What it means to 'read the air'",
        "titleZh": "所谓「读空气」这件事",
        "titleRuby": [],
        "segments": [
            ("日本語には「空気を読む」という表現がある。その場の雰囲気を察して、適切にふるまうことを意味する。",
             "In Japanese there is the expression 'reading the air.' It means sensing the atmosphere of a situation and behaving appropriately.",
             "日语中有「读空气」这个说法。意思是察觉现场的氛围，做出恰当的行为。"),
            ("たとえば、会議で全員が賛成の方向に傾いているとき、一人だけ反対意見を強く主張すると「空気が読めない」と言われることがある。",
             "For example, when everyone at a meeting is leaning toward agreement, if one person strongly insists on an opposing opinion, they may be told they 'can't read the air.'",
             "比如在会议上大家都倾向于赞成时，如果只有一个人强烈主张反对意见，就可能被说「不会读空气」。"),
            ("この感覚は日本独特のものではないが、日本社会では特に重視される傾向がある。",
             "This sensibility is not unique to Japan, but it tends to be especially valued in Japanese society.",
             "这种感觉并非日本独有，但在日本社会中尤为被重视。"),
            ("集団の調和を大切にする文化的背景が、こうした暗黙のルールを生んでいるのだろう。",
             "The cultural background of valuing group harmony likely gives rise to these unspoken rules.",
             "重视集体和谐的文化背景，大概催生了这样的潜规则。"),
            ("空気を読む能力は、円滑な人間関係を築くうえで確かに役に立つ。",
             "The ability to read the air is certainly useful in building smooth interpersonal relationships.",
             "读空气的能力在构建圆滑的人际关系上确实有用。"),
            ("相手が言いにくそうにしていることを先回りして配慮できれば、信頼関係が深まる。",
             "If you can anticipate and show consideration for things the other person finds hard to say, it deepens trust.",
             "如果能先于对方考虑到他们难以启齿的事，信赖关系就会加深。"),
            ("しかし一方で、空気を読みすぎることの弊害も指摘されている。",
             "However, the drawbacks of reading the air too much have also been pointed out.",
             "然而另一方面，过度读空气的弊端也被指出。"),
            ("本音を言えない雰囲気が蔓延すると、組織の中で重要な問題が見過ごされるリスクがある。",
             "When an atmosphere where people can't speak their true feelings prevails, there's a risk that important issues within an organization get overlooked.",
             "当无法说真话的氛围蔓延时，组织中重要的问题就有被忽视的风险。"),
            ("若い世代の中には、必要以上に空気を読むことに疲れを感じている人も増えているという。",
             "Among the younger generation, it's said that more and more people feel exhausted from reading the air more than necessary.",
             "据说年轻一代中，因过度读空气而感到疲惫的人也在增加。"),
            ("SNSの普及もあり、以前よりも率直に意見を述べる傾向が見られるようになった。",
             "With the spread of social media, a trend toward expressing opinions more frankly than before has become visible.",
             "随着社交媒体的普及，也能看到比以前更坦率地发表意见的趋势。"),
            ("空気を読むことと自分の意見を持つこと。この二つのバランスをどう取るかが、現代の日本人に問われている課題かもしれない。",
             "Reading the air and having your own opinion — how to balance these two may be the challenge facing modern Japanese people.",
             "读空气与拥有自己的主见——如何平衡这两者，或许正是摆在现代日本人面前的课题。"),
        ],
    },
    {
        "id": "n2-kuuki-yomu-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "「空気を読む」文化について議論する",
        "titleJp": "「空気を読む」文化について議論する",
        "titleEn": "Debating the culture of 'reading the air'",
        "titleZh": "讨论「读空气」文化",
        "titleRuby": [],
        "sections": [
            section("空気を読む経験", "Experiences of reading the air", "读空气的经历", "💭", [
                ("A", "この前の飲み会で、上司の話がつまらなくても全員笑ってたのを見て、日本って独特だなと思った。",
                 "At the drinking party the other day, I saw everyone laughing even though the boss's story was boring, and I thought Japan is really unique.",
                 "前几天聚餐上，即使上司的话很无聊大家也都在笑，我觉得日本真的很独特。"),
                ("B", "あれは「空気を読む」っていう文化だよね。本音と建前が違うことも多い。",
                 "That's the culture of 'reading the air.' What people really think and what they show are often different.",
                 "那就是「读空气」的文化吧。真心话和表面话往往不一样。"),
                ("A", "僕の国では気に入らなければはっきり言うから、最初はすごく戸惑った。",
                 "In my country, if you don't like something you say so clearly, so at first I was really confused.",
                 "在我的国家不喜欢就会直说，所以一开始非常困惑。"),
                ("B", "慣れるまでは大変だけど、相手への配慮という面もあるから、全否定はできないかな。",
                 "It's tough until you get used to it, but since there's also the aspect of consideration for others, I can't completely reject it.",
                 "习惯之前是很难，但因为也有体谅对方的一面，也不能完全否定。"),
            ]),
            section("変わりつつある価値観", "Changing values", "正在变化的价值观", "🔄", [
                ("A", "でも最近の若い人は、わりとはっきり意見を言う人が増えてきた気がする。",
                 "But I feel like recently more young people are expressing their opinions pretty clearly.",
                 "不过最近的年轻人，直接说出想法的人感觉越来越多了。"),
                ("B", "SNSの影響も大きいと思う。匿名でも意見を発信できるようになったから。",
                 "I think the influence of social media is big. Because people can express opinions even anonymously now.",
                 "我觉得��交媒体的影响也很大。因为即使匿名也能发表意见了。"),
                ("A", "空気を読みつつ、言うべきことは言う。そのバランスが大事なんだろうね。",
                 "Reading the air while still saying what needs to be said. That balance is probably what matters.",
                 "一边读空气一边该说的还是说。这个平衡大概才是最重要的吧。"),
                ("B", "同感。ただ黙って合わせるだけじゃ、結局自分が苦しくなるだけだから。",
                 "I agree. Just silently going along with things will only make yourself suffer in the end.",
                 "同感。只是沉默迎合的话，最终只会让自己痛苦。"),
            ]),
        ],
    },

    # ===== 3. 都会と地方 =====
    {
        "id": "n2-urban-rural-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "都会と地方、どちらに住むか",
        "titleJp": "都会と地方、どちらに住むか",
        "titleEn": "City or countryside — where to live?",
        "titleZh": "城市还是乡下，住哪里好",
        "titleRuby": [],
        "segments": [
            ("大学卒業後、東京で就職するか地元に戻るかで迷っている若者は少なくない。",
             "After graduating from college, many young people are torn between finding work in Tokyo or returning to their hometown.",
             "大学毕业后，不少年轻人在去东京就职还是回老家之间犹豫不决。"),
            ("東京には仕事の選択肢が多く、文化的な刺激にも恵まれている。",
             "Tokyo offers many job options and is rich in cultural stimulation.",
             "东京工作机会多，文化刺激也很丰富。"),
            ("しかし、家賃の高さや通勤ラッシュのストレスは無視できない。",
             "However, the high rent and commuting rush stress cannot be ignored.",
             "然而，高额的房租和通勤高峰的压力不容忽视。"),
            ("一方、地方では自然が豊かで、生活費も比較的安い。",
             "On the other hand, rural areas are rich in nature and the cost of living is relatively low.",
             "另一方面，地方自然丰富，生活费也比较便宜。"),
            ("子育てをするなら広い家に住めるし、地域のつながりも強い。",
             "For raising children, you can live in a spacious house, and community ties are strong.",
             "如果养育孩子，可以住大房子，社区联系也很紧密。"),
            ("ただし、地方は求人が限られており、若者にとって魅力的な仕事が見つかりにくいという現実がある。",
             "However, job openings in rural areas are limited, and the reality is that it's hard for young people to find attractive jobs.",
             "不过，地方的招聘机会有限，年轻人难以找到有吸引力的工作，这是现实。"),
            ("近年、リモートワークの普及により、地方に移住しながら都会の会社で働くという選択肢も生まれた。",
             "In recent years, with the spread of remote work, the option of moving to the countryside while working for a city company has also emerged.",
             "近年来随着远程办公的普及，搬到地方的同时为城市公司工作的选择也出现了。"),
            ("実際に移住した人からは「通勤がなくなって生活に余裕ができた」という声がある。",
             "People who have actually moved say things like, 'With no commute, I have more breathing room in life.'",
             "实际搬过去的人说「没有通勤后生活变得宽裕了」。"),
            ("しかし、移住先でのコミュニティに溶け込めず、孤立するケースも報告されている。",
             "However, cases of people failing to integrate into communities at their new homes and becoming isolated have also been reported.",
             "不过，也有报道称在移居地无法融入社区而孤立的案例。"),
            ("都会と地方のどちらが優れているかという問いに、唯一の正解はない。",
             "There is no single right answer to the question of whether city or countryside is better.",
             "城市和地方哪个更好这个问题，没有唯一的正确答案。"),
            ("大切なのは、自分の価値観やライフスタイルに合った場所を選ぶことではないだろうか。",
             "What matters is perhaps choosing a place that matches your own values and lifestyle.",
             "重要的或许是选择符合自己价值观和生活方式的地方吧。"),
        ],
    },
    {
        "id": "n2-urban-rural-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "都会暮らしと地方移住を比較する",
        "titleJp": "都会暮らしと地方移住を比較する",
        "titleEn": "Comparing city life and moving to the countryside",
        "titleZh": "比较城市生活和移居地方",
        "titleRuby": [],
        "sections": [
            section("都会の良さと辛さ", "Pros and cons of the city", "城市的好与苦", "🏙️", [
                ("A", "東京に住んでもう五年になるけど、やっぱり家賃が高すぎるなと思うことがある。",
                 "I've been living in Tokyo for five years now, but I still sometimes think the rent is just too high.",
                 "住东京已经五年了，但还是会觉得房租太贵了。"),
                ("B", "わかる。ワンルームで八万円って、地方じゃ考えられないよね。",
                 "I know. 80,000 yen for a studio — unthinkable in the countryside.",
                 "懂的。一个单间八万日元，在地方简直不可想象。"),
                ("A", "でも仕事の数は圧倒的に多いし、転職もしやすい。",
                 "But there are overwhelmingly more jobs, and it's easier to switch careers.",
                 "但是工作机会压倒性地多，跳槽也容易。"),
                ("B", "それは確かに。地元に帰ったら、今と同じ給料はもらえないだろうし。",
                 "That's true. If I went back home, I probably couldn't get the same salary.",
                 "这倒是。回老家的话，大概拿不到现在的工资。"),
            ]),
            section("地方移住への関心", "Interest in rural migration", "对移居地方的关注", "🏡", [
                ("A", "最近、リモートワークで地方に引っ越した同期がいるんだけど、すごく幸せそうだった。",
                 "Recently a colleague who joined at the same time moved to the countryside for remote work, and they looked really happy.",
                 "最近有个同期因为远程办公搬去了地方，看起来特别幸福。"),
                ("B", "どこに引っ越したの？",
                 "Where did they move to?",
                 "搬到哪里了？"),
                ("A", "長野の山の近くらしい。家賃は東京の半分以下で、庭付きの一軒家だって。",
                 "Apparently near the mountains in Nagano. Rent is less than half of Tokyo, a house with a garden.",
                 "好像是长野山附近。房租不到东京的一半，还是带院子的独栋。"),
                ("B", "うらやましいな。ただ、買い物とか不便じゃないのかな。",
                 "I'm jealous. But I wonder if shopping and stuff isn't inconvenient.",
                 "好羡慕。不过购物什么的不会不方便吗。"),
                ("A", "車は必須らしいけど、ネットスーパーもあるし、慣れれば問題ないって言ってた。",
                 "Apparently a car is essential, but with online supermarkets and all, they said it's no problem once you get used to it.",
                 "说是必须有车，但也有网上超市，习惯了就没问题。"),
                ("B", "結局、何を優先するかだよね。便利さか、ゆとりか。",
                 "In the end, it's about what you prioritize, right? Convenience or space.",
                 "归根结底是看你优先考虑什么吧。便利还是从容。"),
            ]),
        ],
    },

    # ===== 4. 一人暮らし =====
    {
        "id": "n2-living-alone-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "一人暮らしを始めて気づいたこと",
        "titleJp": "一人暮らしを始めて気づいたこと",
        "titleEn": "Things I realized after starting to live alone",
        "titleZh": "开始独居后发现的事",
        "titleRuby": [],
        "segments": [
            ("大学に入学したのを機に、実家を出て一人暮らしを始めた。",
             "Taking the opportunity of entering university, I left my parents' house and started living alone.",
             "以上大学为契机，离开了老家开始独居。"),
            ("最初の一か月は自由を満喫していたが、すぐに現実の壁にぶつかった。",
             "For the first month I was enjoying my freedom, but I quickly hit the wall of reality.",
             "第一个月尽情享受自由，但很快就撞上了现��的墙。"),
            ("まず、料理がまったくできなかった。毎日コンビニ弁当を食べていたら、体調を崩した。",
             "First, I couldn't cook at all. When I ate convenience store bento every day, I got sick.",
             "首先是完全不会做饭。每天吃便利店便当后身体出了问题。"),
            ("仕方なく自炊を始めたが、最初はご飯を炊くだけでも一苦労だった。",
             "I reluctantly started cooking for myself, but at first even just cooking rice was a struggle.",
             "没办法开始自己做饭，但最初光是煮个饭都费劲。"),
            ("洗濯も、白い服と色物を一緒に洗って全部ピンクにしてしまったことがある。",
             "With laundry too, I once washed whites and colors together and turned everything pink.",
             "洗衣服也是，曾经把白衣服和有颜色的一起洗，全染成粉色了。"),
            ("光熱費の請求書を見て、エアコンをつけっぱなしにしていたことを反省した。",
             "When I saw the utility bill, I regretted leaving the air conditioner on all the time.",
             "看到水电费账单后，反省了一直开着空调的事。"),
            ("しかし半年も経つと、少しずつ生活のリズムができてきた。",
             "But after about half a year, I gradually found my rhythm.",
             "不过过了半年左右，生活的节奏渐渐形成了。"),
            ("自分でお金を管理し、家事をこなし、体調にも気を配るようになった。",
             "I began managing my own money, handling housework, and paying attention to my health.",
             "开始自己管钱、做家务，也注意起了身体状况。"),
            ("一人暮らしで最も大きな収穫は、親のありがたみに気づいたことだと思う。",
             "I think the biggest gain from living alone was realizing how grateful I should be to my parents.",
             "我觉得独居最大的收获是意识到了父母的可贵。"),
            ("今まで当たり前だと思っていた食事や掃除が、すべて誰かの手で行われていたのだ。",
             "The meals and cleaning I had taken for granted were all done by someone's hands.",
             "一直觉得理所当然的饭菜和打扫，全都是有人在做的。"),
            ("一人暮らしは大変なことも多いが、人を確実に成長させてくれる経験だと思う。",
             "Living alone has many challenges, but I believe it's an experience that definitely helps you grow.",
             "独居虽然辛苦的事很多，但我认为它是一段确实能让人成长的经历。"),
        ],
    },
    {
        "id": "n2-living-alone-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "一人暮らしの苦労を語り合う",
        "titleJp": "一人暮らしの苦労を語り合う",
        "titleEn": "Sharing the struggles of living alone",
        "titleZh": "互相聊独居的辛苦",
        "titleRuby": [],
        "sections": [
            section("自炊と家事", "Cooking and housework", "做饭和家务", "🍳", [
                ("A", "一人暮らし始めてから、親のありがたみが身に沁みるようになった。",
                 "Since I started living alone, I've come to deeply appreciate my parents.",
                 "开始独居后，深深体会到了父母的可贵。"),
                ("B", "わかる。毎日ご飯を作ってくれてたのって、本当にすごいことだったんだね。",
                 "I know. Making meals every day was really something amazing, wasn't it.",
                 "懂的。每天做饭真的是很了不起的事啊。"),
                ("A", "最初の頃、毎晩カップ麺を食べてたら、顔にニキビがすごいことになった。",
                 "In the beginning, when I ate cup noodles every night, my face broke out terribly.",
                 "刚开始的时候每晚吃泡面，脸上长了好多痘。"),
                ("B", "私は洗濯物をため込みすぎて、着る服がなくなったことがある。",
                 "I once let my laundry pile up so much that I had nothing to wear.",
                 "我有过攒了太多脏衣服、没衣服穿的时候。"),
            ]),
            section("お金の管理", "Managing money", "管钱", "💸", [
                ("A", "光熱費の請求が来たとき、こんなにかかるのかって驚いたよ。",
                 "When the utility bill came, I was shocked at how much it cost.",
                 "水电费账单来的时候，惊讶居然这么贵。"),
                ("B", "冬のガス代が特にやばいよね。シャワーの時間を短くするようになった。",
                 "Winter gas bills are especially bad. I started shortening my shower time.",
                 "冬天的煤气费特别吓人。后来就缩短了洗澡时间。"),
                ("A", "節約しようと思って家計簿をつけ始めたんだけど、三日で挫折した。",
                 "I tried to save money by keeping a household budget, but I gave up after three days.",
                 "想省钱就开始记账，结果三天就放弃了。"),
                ("B", "アプリを使うと楽だよ。レシートを撮るだけで自動で記録してくれるやつがある。",
                 "Using an app makes it easier. There's one that records everything automatically just by taking a photo of the receipt.",
                 "用app就轻松了。有那种拍一下收据就自动记录的。"),
                ("A", "それはいいね。やっぱり一人暮らしって、生活力が試されるよね。",
                 "That sounds great. Living alone really tests your life skills, doesn't it.",
                 "那不错。果然独居就是考验生活能力啊。"),
            ]),
        ],
    },

    # ===== 5. 外国人として日本で働く =====
    {
        "id": "n2-foreigner-work-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "外国人として日本で働くということ",
        "titleJp": "外国人として日本で働くということ",
        "titleEn": "What it means to work in Japan as a foreigner",
        "titleZh": "作为外国人在日本工作这件事",
        "titleRuby": [],
        "segments": [
            ("日本語学校を卒業してから、IT企業に就職して三年になる。",
             "It's been three years since I graduated from Japanese language school and joined an IT company.",
             "从日语学校毕业后进了IT公司，已经三年了。"),
            ("面接では「なぜ日本で働きたいのか」と聞かれ、技術力の高さと仕事への姿勢を学びたいと答えた。",
             "In the interview, when asked 'Why do you want to work in Japan?' I said I wanted to learn from the high technical skills and work attitude.",
             "面试时被问「为什么想在日本工作」，我回答说想学习高超的技术力和工作态度。"),
            ("入社してまず驚いたのは、報連相という文化だった。",
             "The first thing that surprised me after joining was the culture of 'ho-ren-so' (report, contact, consult).",
             "入职后最先让我惊讶的是报联商的文化。"),
            ("報告・連絡・相談を細かく行うことが、信頼を築く基本だと教わった。",
             "I was taught that carefully carrying out reporting, contacting, and consulting is the foundation of building trust.",
             "我被告知细致地进行汇报、联络、商量是建立信任的基础。"),
            ("最初は「こんなことまで報告するのか」と思ったが、今では合理的だと感じている。",
             "At first I thought, 'Do I really need to report even this?' but now I find it reasonable.",
             "一开始觉得「连这种事也要汇报吗」，但现在觉得很合理。"),
            ("言語の壁は今でもゼロではない。敬語の使い分けや、曖昧な表現の理解に苦労することがある。",
             "The language barrier hasn't completely disappeared even now. I sometimes struggle with using different levels of keigo and understanding ambiguous expressions.",
             "语言的障碍至今也不是完全没有。敬语的区分使用和理解模糊表达有时还是很吃力。"),
            ("特にメールの書き方は独特で、定型表現を覚えるのに時間がかかった。",
             "Especially the way emails are written is unique, and it took time to learn the set phrases.",
             "尤其是邮件的写法很独特，记住固定表达花了不少时间。"),
            ("ただ、同僚は親切な人が多く、困ったときはいつも助けてくれた。",
             "However, most of my colleagues are kind, and they always helped me when I was in trouble.",
             "不过同事大多很亲切，遇到困难时总是帮助我。"),
            ("外国人であることが不利に働く場面がないわけではないが、能力を認めてもらえれば正当に評価される環境だと思う。",
             "It's not that being a foreigner never works against you, but I think it's an environment where you're fairly evaluated if your abilities are recognized.",
             "当外国人不利的场面也不是没有，但我觉得只要能力被认可就能得到公正的评价。"),
            ("異文化の中で働くことは簡単ではないが、視野が広がるという意味では何物にも代えがたい経験だ。",
             "Working in a different culture isn't easy, but in the sense of broadening your perspective, it's an irreplaceable experience.",
             "在异文化中工作并不轻松，但从拓宽视野的角度来说，是无可替代的经历。"),
            ("今後も日本で経験を積み、いずれは母国と日本をつなぐ仕事がしたいと考えている。",
             "I plan to continue gaining experience in Japan, and eventually I want to do work that connects my home country and Japan.",
             "今后也打算在日本积累经验，将来想做连接母国和日本的工作。"),
        ],
    },
    {
        "id": "n2-foreigner-work-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "日本の職場文化について外国人同士で話す",
        "titleJp": "日本の職場文化について外国人同士で話す",
        "titleEn": "Foreigners discussing Japanese workplace culture",
        "titleZh": "外国人之间聊日本的职场文化",
        "titleRuby": [],
        "sections": [
            section("報連相と会議", "Ho-ren-so and meetings", "报联商和会议", "💼", [
                ("A", "日本の会社に入って一番びっくりしたのは、報連相の文化かな。",
                 "The thing that surprised me most after joining a Japanese company is probably the ho-ren-so culture.",
                 "进日本公司后最惊讶的大概是报联商的文化吧。"),
                ("B", "わかる。些細なことでも上司に報告しないといけないのは、最初は窮屈だった。",
                 "I know. Having to report even trivial things to your boss felt restrictive at first.",
                 "懂的。连小事也要向上司汇报，一开始觉得好拘束。"),
                ("A", "会議も多いよね。三十分で終わる内容を一時間かけて話し合うことがある。",
                 "There are a lot of meetings too. Sometimes they spend an hour discussing what could be settled in thirty minutes.",
                 "会议也多。三十分钟能讲完的内容有时要讨论一个小时。"),
                ("B", "ただ、合意形成を大切にしてるからこそ、あとで揉めることが少ないのかもしれない。",
                 "But maybe because they value consensus-building, there are fewer conflicts later.",
                 "不过也许正因为重视达成共识，之后产生矛盾的情况才会少。"),
            ]),
            section("言語と人間関係", "Language and relationships", "语言和人际关系", "🗣️", [
                ("A", "敬語は三年経った今でも完璧には使えない。尊敬語と謙譲語がごちゃ混ぜになる。",
                 "Even after three years I still can't use keigo perfectly. Honorific and humble forms get mixed up.",
                 "敬语过了三年还是用不完美。尊敬语和谦让语会搞混。"),
                ("B", "メールの冒頭の挨拶文も難しいよね。「お世話になっております」を何百回書いたことか。",
                 "The greeting phrases at the beginning of emails are hard too. I wonder how many hundreds of times I've written 'thank you for your continued support.'",
                 "邮件开头的问候语也难。「承蒙关照」不知道写了几百遍了。"),
                ("A", "でも同僚に恵まれたおかげで、だいぶ助けられてる。",
                 "But thanks to having great colleagues, I've been helped a lot.",
                 "不过多亏了遇到好同事，帮了我很多。"),
                ("B", "うん。言葉が不完全でも、一生懸命やっていれば認めてもらえるよね。",
                 "Yeah. Even if your language isn't perfect, if you work hard, people will recognize you.",
                 "嗯。就算语言不完美，只要认真做的话就会被认可。"),
                ("A", "異文化で働くのは大変だけど、自分の成長にはなっていると思う。",
                 "Working in a different culture is tough, but I think it's contributing to my growth.",
                 "在异文化中工作虽然辛苦，但我觉得对自身的成长是有帮助的。"),
            ]),
        ],
    },

    # ===== 6. 趣味が仕事に =====
    {
        "id": "n2-hobby-to-job-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "趣味が仕事になった日",
        "titleJp": "趣味が仕事になった日",
        "titleEn": "The day my hobby became my job",
        "titleZh": "兴趣变成工作的那天",
        "titleRuby": [],
        "segments": [
            ("学生時代から写真が好きで、週末になるとカメラを持って街を歩き回っていた。",
             "I've loved photography since I was a student, and on weekends I'd walk around the city with my camera.",
             "从学生时代起就喜欢摄影，一到周末就拿着相机在街上到处走。"),
            ("SNSに作品を投稿していたところ、ある企業から「うちの商品を撮ってほしい」と連絡が来た。",
             "When I was posting my work on social media, a company contacted me saying, 'We'd like you to photograph our products.'",
             "在社交媒体上发布作品时，有家公司联系我说「想请你拍我们的产品」。"),
            ("最初は副業として引き受けたが、口コミで依頼が増え、やがて本業になった。",
             "At first I took it on as a side job, but requests grew through word of mouth, and eventually it became my main work.",
             "一开始当副业接的，但通过口碑介绍委托越来越多，渐渐就成了主业。"),
            ("趣味が仕事になると聞くと楽しそうに思えるが、現実はそう甘くない。",
             "When you hear that a hobby has become a job, it sounds fun, but the reality isn't that simple.",
             "听到兴趣变成工作觉得很开心，但现实没那么美好。"),
            ("クライアントの要望に応えなければならず、自分の撮りたいものだけを撮るわけにはいかない。",
             "You have to meet the client's requests, and you can't just photograph only what you want to.",
             "必须满足客户的需求，不能只拍自己想拍的东西。"),
            ("締め切りに追われて徹夜することもあるし、収入が不安定な月もある。",
             "There are times I stay up all night chasing deadlines, and some months my income is unstable.",
             "也有被截止日期追着通宵的时候，也有收入不稳定的月份。"),
            ("それでも、自分の撮った写真が広告や雑誌に載ったときの達成感は格別だ。",
             "Still, the sense of achievement when my photos appear in ads or magazines is exceptional.",
             "即便如此，自己拍的照片刊登在广告或杂志上时的成就感是非凡的。"),
            ("好きなことで生計を立てるには、技術だけでなく、営業力や自己管理能力も求められる。",
             "Making a living from what you love requires not just skill, but also sales ability and self-management.",
             "靠喜欢的事谋生，不仅需要技术，还需要营销能力和自我管理能力。"),
            ("もし趣味を仕事にしたいと考えている人がいるなら、まずは副業から始めてみることをおすすめする。",
             "If anyone is thinking of turning their hobby into work, I'd recommend starting with it as a side job first.",
             "如果有人想把兴趣变成工作，建议先从副业开始尝试。"),
            ("好きなことに全力を注げる人生は、たとえ楽ではなくても、充実していると断言できる。",
             "A life where you can pour all your energy into what you love — even if it's not easy, I can say with certainty that it's fulfilling.",
             "能全力投入喜欢的事的人生，即使不轻松，我也可以断言它是充实的。"),
        ],
    },
    {
        "id": "n2-hobby-to-job-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "好きなことを仕事にすることについて話す",
        "titleJp": "好きなことを仕事にすることについて話す",
        "titleEn": "Talking about making what you love your job",
        "titleZh": "聊把喜欢的事变成工作",
        "titleRuby": [],
        "sections": [
            section("きっかけ", "The trigger", "契机", "📸", [
                ("A", "写真が仕事になったって聞いたけど、どうやって始まったの？",
                 "I heard photography became your job — how did it start?",
                 "听说摄影变成了你的工作，是怎么开始的？"),
                ("B", "SNSに載せてた写真を見た会社から連絡が来たのがきっかけかな。",
                 "It started when a company reached out after seeing photos I'd posted on social media.",
                 "契机大概是有公司看到我在社交媒体上发的照片后联系了我。"),
                ("A", "それはすごいね。最初から仕事にしようと思ってたの？",
                 "That's amazing. Were you planning to make it your job from the start?",
                 "好厉害啊。一开始就打算当工作的吗？"),
                ("B", "全然。最初は副業のつもりだったけど、依頼が増えて気づいたら本業になってた。",
                 "Not at all. At first I planned it as a side job, but requests kept coming and before I knew it, it was my main work.",
                 "完全没有。一开始打算当副业，但委托越来越多，不知不觉就成了主业。"),
            ]),
            section("現実と理想", "Reality and ideals", "现实和理想", "⚖️", [
                ("A", "好きなことが仕事って、毎日楽しそうだけど、大変なこともあるんじゃない？",
                 "Having your hobby as your job sounds fun every day, but aren't there tough parts too?",
                 "喜欢的事当工作，看起来每天都很开心，但也有辛苦的地方吧？"),
                ("B", "もちろん。クライアントの要望と自分のこだわりが合わないこともあるし、収入が安定しない時期もある。",
                 "Of course. Sometimes the client's requests don't match my vision, and there are periods when income isn't stable.",
                 "当然。客户的需求和自己的坚持不一致的时候也有，收入不稳定的时期也有。"),
                ("A", "それでも続けられるのは、やっぱり好きだからなのかな。",
                 "But you keep going — is it because you love it after all?",
                 "即便如此还能坚持，果然还是因为喜欢吧。"),
                ("B", "うん。自分の写真が誰かの役に立ってると思うと、もっと頑張ろうって思える。",
                 "Yeah. When I think my photos are helping someone, it motivates me to work harder.",
                 "嗯。想到自己的照片对谁有帮助���就会觉得想更加努力。"),
                ("A", "いいなあ。僕もいつか、好きなことで食べていけるようになりたいな。",
                 "That's nice. I hope someday I can make a living doing what I love too.",
                 "真好啊。我也想有一天能靠喜欢的事养活自己。"),
            ]),
        ],
    },

    # ===== 7. キャッシュレス =====
    {
        "id": "n2-cashless-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "キャッシュレス社会の光と影",
        "titleJp": "キャッシュレス社会の光と影",
        "titleEn": "The light and shadow of a cashless society",
        "titleZh": "无现金社会的利与弊",
        "titleRuby": [],
        "segments": [
            ("ここ数年で、日本でもキャッシュレス決済が急速に普及した。",
             "In the past few years, cashless payment has rapidly spread in Japan as well.",
             "近几年，无现金支付在日本也迅速普及了。"),
            ("スマホ一つで電車に乗り、買い物をし、レストランで食事ができる。",
             "With just a smartphone, you can ride trains, shop, and dine at restaurants.",
             "只用一部手机就能坐电车、购物、在餐厅吃饭。"),
            ("政府もポイント還元キャンペーンなどを通じて、キャッシュレス化を推進してきた。",
             "The government has been promoting cashless adoption through point reward campaigns and other measures.",
             "政府也通过积分返还活动等措施推进无现金化。"),
            ("消費者にとっての利点は明らかだ。会計が速く、小銭を持ち歩く必要がない。",
             "The benefits for consumers are clear: payments are fast and there's no need to carry coins.",
             "对消费者来说好处是显而易见的。结账快，不需要带零钱。"),
            ("利用履歴が自動で残るため、家計の管理もしやすくなった。",
             "Since transaction history is automatically saved, managing household finances has also become easier.",
             "由于消费记录自动保存，家庭财务管理也变得更方便了。"),
            ("店舗側にもメリットがある。現金の管理コストが減り、レジ締めの時間も短縮される。",
             "There are also benefits for shops. Cash management costs decrease and closing the register takes less time.",
             "对店铺来说也有好处。现金管理成本降低，收银结账时间也缩短了。"),
            ("しかし、課題がないわけではない。高齢者の中にはスマホの操作に不慣れな人も多い。",
             "However, it's not without issues. Many elderly people are unfamiliar with smartphone operations.",
             "然而也并非没有课题。老年人中不熟悉智能手机操作的人也很多。"),
            ("また、災害時に停電が起きると、電子決済が使えなくなるリスクもある。",
             "Also, there's the risk that electronic payments become unusable when power outages occur during disasters.",
             "此外，灾害时停电的话电子支付就无法使用的风险也存在。"),
            ("個人情報の流出やサイバー犯罪への懸念も、完全には払拭されていない。",
             "Concerns about personal data leaks and cybercrime haven't been completely dispelled either.",
             "对个人信息泄露和网络犯罪的担忧也没有被完全消除。"),
            ("現金を完全になくすのではなく、デジタルと現金の共存が現実的な解ではないだろうか。",
             "Rather than completely eliminating cash, wouldn't the coexistence of digital and cash be a realistic solution?",
             "与其完全消灭现金，数字和现金共存或许才是现实的解决方案吧。"),
            ("テクノロジーの恩恵を受けつつ、取り残される人がいない社会を目指すことが重要だ。",
             "It's important to aim for a society where no one is left behind while benefiting from technology.",
             "在享受科技红利的同时，建设一个不让任何人掉队的社会是重要的。"),
        ],
    },
    {
        "id": "n2-cashless-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "キャッシュレスの便利さとリスクを話し合う",
        "titleJp": "キャッシュレスの便利さとリスクを話し合う",
        "titleEn": "Discussing the convenience and risks of going cashless",
        "titleZh": "讨论无现金的便利与风险",
        "titleRuby": [],
        "sections": [
            section("普段の使い方", "Everyday usage", "日常使用", "💳", [
                ("A", "最近、財布を持ち歩かなくなったんだけど、同じ人いる？",
                 "I've stopped carrying a wallet recently — anyone else the same?",
                 "最近不带钱包出门了，有人一样吗？"),
                ("B", "私もスマホだけで出かけることが増えた。現金を使うのは月に一度くらいかも。",
                 "I also go out with just my phone more often. Maybe I use cash only once a month.",
                 "我也越来越多只带手机出门了。大概一个月才用一次现金。"),
                ("A", "コンビニもスーパーも交通機関も、ほぼ全部スマホで済むもんね。",
                 "Convenience stores, supermarkets, public transport — almost everything can be done with your phone.",
                 "便利店、超市、交通工具，几乎全部都能用手机搞定。"),
                ("B", "ポイントも貯まるし、支出の管理もアプリで見られるから、現金より効率がいい。",
                 "You earn points too, and you can check your spending on the app, so it's more efficient than cash.",
                 "还能攒积分，支出管理也能在app上看，比现金效率高。"),
            ]),
            section("リスクと課題", "Risks and challenges", "风险与课题", "⚠️", [
                ("A", "ただ、この間の台風で停電したとき、スマホの充電が切れて何も買えなくて焦った。",
                 "But when the power went out during the recent typhoon, my phone died and I panicked because I couldn't buy anything.",
                 "不过上次台风停电的时候，手机没电了什么都买不了，好着急。"),
                ("B", "それは怖いね。やっぱり非常時のために、ある程度の現金は持っておくべきかも。",
                 "That's scary. Maybe we should keep some cash on hand for emergencies after all.",
                 "那好可怕。果然为了紧急情况还是应该带一些现金。"),
                ("A", "あと、祖父母の世代はスマホ決済に抵抗がある人も多いらしいよ。",
                 "Also, apparently many people in our grandparents' generation resist smartphone payments.",
                 "还有，祖父母那一代对手机支付有抵触的人好像也很多。"),
                ("B", "全員がデジタルに移行できるわけじゃないからね。現金との共存が大事だと思う。",
                 "Not everyone can transition to digital. I think coexistence with cash is important.",
                 "毕竟不是所有人都能转向数字化。我觉得和现金共存很重要。"),
            ]),
        ],
    },

    # ===== 8. テレワーク =====
    {
        "id": "n2-telework-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "テレワークが変えた働き方",
        "titleJp": "テレワークが変えた働き方",
        "titleEn": "How telework changed the way we work",
        "titleZh": "远程办公改变的工作方式",
        "titleRuby": [],
        "segments": [
            ("二〇二〇年以降、感染症対策をきっかけに、多くの企業がテレワークを導入した。",
             "Since 2020, prompted by pandemic measures, many companies introduced telework.",
             "2020年以后，以疫情防控为契机，许多企业引入了远程办公。"),
            ("当初は一時的な措置と思われていたが、その後も継続する企業は少なくない。",
             "Initially it was thought to be a temporary measure, but many companies have continued it since.",
             "当初被认为是临时措施，但之后继续实施的企业不在少数。"),
            ("テレワークの最大の利点は、通勤時間がなくなることだろう。",
             "The biggest advantage of telework is probably the elimination of commuting time.",
             "远程办公最大的好处大概是不用通勤了。"),
            ("片道一時間の通勤をしていた人にとっては、一日二時間の余裕が生まれる計算になる。",
             "For someone who commuted one hour each way, that works out to two hours of extra time per day.",
             "对单程通勤一小时的人来说，相当于每天多出两个小时。"),
            ("その時間を趣味や家族との団らんに使えるようになったという声は多い。",
             "Many say they can now use that time for hobbies or spending time with family.",
             "很多人说可以把这些时间用在兴趣爱好或家人的团聚上了。"),
            ("育児中の社員にとっても、在宅勤務は大きな助けになっている。",
             "For employees raising children, working from home has also been a great help.",
             "对正在养育孩子的员工来说，在家办公也是很大的帮助。"),
            ("一方で、オンとオフの切り替えが難しいという問題もある。",
             "On the other hand, there's also the problem of difficulty switching between work and personal time.",
             "另一方面，也有工作和生活难以切换的问题。"),
            ("自宅にいると、ついダラダラと仕事を続けてしまい、労働時間がかえって長くなるケースもある。",
             "When you're at home, you may end up working sluggishly, and working hours can actually become longer.",
             "在家里的话，容易拖拖拉拉地继续工作，反而导致工作时间变长的情况也有。"),
            ("また、雑談やちょっとした相談がしにくくなり、孤独感を覚える人もいる。",
             "Also, casual conversations and quick consultations become harder, and some people feel lonely.",
             "此外，闲聊和简短的商量变得困难，也有人感到孤独。"),
            ("チームの一体感が薄れることを懸念して、週に数日は出社を義務づける企業も出てきた。",
             "Concerned about a weakening sense of team unity, some companies have started requiring employees to come to the office several days a week.",
             "因为担心团队凝聚力减弱，也出现了要求每周几天到公司上班的企业。"),
            ("完全な出社回帰か、完全なテレワークかではなく、両者を組み合わせたハイブリッド型が主流になりつつある。",
             "Rather than a full return to the office or full telework, a hybrid model combining both is becoming mainstream.",
             "不是完全恢复到办公室，也不是完全远程，而是两者结合的混合型正在成为主流。"),
            ("働き方の選択肢が増えたことは、間違いなく社会の進歩と言えるだろう。",
             "The increase in work style options can undoubtedly be called social progress.",
             "工作方式的选择增多了，这无疑可以说是社会的进步。"),
        ],
    },
    {
        "id": "n2-telework-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "テレワークのメリットとデメリットを語る",
        "titleJp": "テレワークのメリットとデメリットを語る",
        "titleEn": "Discussing the pros and cons of telework",
        "titleZh": "聊远程办公的利弊",
        "titleRuby": [],
        "sections": [
            section("テレワークの良い面", "The good side of telework", "远程办公的好处", "🏠", [
                ("A", "テレワークになってから、朝の満員電車に乗らなくていいのが本当にありがたい。",
                 "Since I started teleworking, I'm really grateful I don't have to ride the packed morning train.",
                 "开始远程办公后，真的很感激不用坐早高峰的拥挤电车了。"),
                ("B", "わかる。往復二時間の通勤がなくなっただけで、生活の質が全然違う。",
                 "I know. Just eliminating the two-hour round-trip commute makes the quality of life completely different.",
                 "懂的。光是没了往返两小时的通勤，生活质量就完全不一样了。"),
                ("A", "空いた時間で料理するようになって、健康にもなった気がする。",
                 "I've started cooking with the spare time, and I feel healthier too.",
                 "用空出来的时间开始做饭了，感觉也变健康了。"),
                ("B", "子どもの送り迎えも自分でできるようになったのが大きいな。",
                 "Being able to drop off and pick up my kids myself has been a big deal.",
                 "能自己接送孩子了，这点影响很大。"),
            ]),
            section("課題と対策", "Challenges and solutions", "课题和对策", "🔧", [
                ("A", "ただ、仕事とプライベートの境目がなくなって、気づいたら夜十時まで働いてることがある。",
                 "But the boundary between work and personal life disappears, and sometimes I find myself working until 10 p.m.",
                 "不过工作和私生活的界限消失了，有时候不知不觉就干到晚上十点。"),
                ("B", "それ、意識的にパソコンを閉じる時間を決めないと、どんどん長くなるよね。",
                 "If you don't consciously set a time to close your laptop, it just keeps getting longer.",
                 "那个如果不有意识地规定关电脑的时间，就会越来越长。"),
                ("A", "あと、ちょっとした雑談ができないのが意外と辛い。孤独を感じることがある。",
                 "Also, not being able to have casual chats is surprisingly tough. I sometimes feel lonely.",
                 "还有，不能随便闲聊这点意外地难受。有时候会感到孤独。"),
                ("B", "うちの会社は週二回出社日を設けて、対面のコミュニケーションを確保してるよ。",
                 "My company has set up two office days a week to ensure face-to-face communication.",
                 "我们公司设定了每周两天出社日，确保面对面的沟通。"),
                ("A", "ハイブリッド型がいちばんバランスがいいのかもしれないね。",
                 "A hybrid model might have the best balance.",
                 "混合型或许是平衡最好的吧。"),
            ]),
        ],
    },

    # ===== 9. 少子化 =====
    {
        "id": "n2-declining-birthrate-essay",
        "level": "N2",
        "format": "essay",
        "titleWord": "少子化と町の変化",
        "titleJp": "少子化と町の変化",
        "titleEn": "Declining birthrate and changes in the town",
        "titleZh": "少子化与街区的变化",
        "titleRuby": [],
        "segments": [
            ("日本の出生率は過去最低を更新し続けており、少子化は深刻な社会問題となっている。",
             "Japan's birth rate continues to hit record lows, and the declining birthrate has become a serious social issue.",
             "日本的出生率持续刷新历史最低，少子化已成为严重的社会问题。"),
            ("私の地元でも、子どもの減少による変化は至るところに見られる。",
             "In my hometown too, changes caused by the decrease in children are visible everywhere.",
             "在我的老家，因孩子减少而产生的变化也随处可见。"),
            ("かつて児童で賑わっていた小学校は統廃合され、校舎は地域の交流施設に転用された。",
             "The elementary school that once bustled with children has been consolidated and the building repurposed as a community facility.",
             "曾经热闹着学生的小学被合并了，校舍被改建成了地区交流设施。"),
            ("商店街では子ども服の店が閉まり、代わりにデイサービスの施設が増えた。",
             "On the shopping street, children's clothing stores have closed, replaced by more daycare service facilities.",
             "商店街里儿童服装店关门了，取而代之的是日间护理设施增多了。"),
            ("公園に行っても子どもの姿はまばらで、遊具が撤去されたところもある。",
             "Even going to the park, children are sparse, and some playground equipment has been removed.",
             "去公园也看不到几个孩子，有的游乐设施也被拆了。"),
            ("少子化の背景には、経済的な不安や働き方の問題が複雑に絡み合っている。",
             "Behind the declining birthrate, economic anxiety and work-style issues are complexly intertwined.",
             "少子化的背后，经济不安和工作方式的问题复杂交织在一起。"),
            ("子どもを一人育てるのにかかる費用は年々増加しており、若い世代の負担は重い。",
             "The cost of raising one child increases every year, placing a heavy burden on the younger generation.",
             "养育一个孩子的费用逐年增加，年轻一代的负担很重。"),
            ("保育所の不足や長時間労働など、子育てと仕事の両立が難しい環境も課題だ。",
             "The shortage of nurseries and long working hours — an environment where it's hard to balance childcare and work — is also a challenge.",
             "托儿所不足、长时间劳动等，难以兼顾育儿和工作的环境也是课题。"),
            ("政府は児童手当の拡充や育児休業制度の改善を進めているが、効果はまだ限定的だ。",
             "The government is expanding child allowances and improving parental leave systems, but the effects are still limited.",
             "政府正在扩大儿童津贴和改善育儿假制度，但效果还很有限。"),
            ("少子化は一朝一夕に解決できる問題ではないが、社会全体で取り組む必要がある。",
             "The declining birthrate is not a problem that can be solved overnight, but the whole society needs to work on it.",
             "少子化不是一朝一夕能解决的问题，但需要整个社会共同应对。"),
            ("子どもが安心して育つことのできる環境づくりが、未来への投資となるはずだ。",
             "Creating an environment where children can grow up with peace of mind should be an investment in the future.",
             "营造一个让孩子能安心成长的环境，应该就是对未来的投资。"),
        ],
    },
    {
        "id": "n2-declining-birthrate-dialogue",
        "level": "N2",
        "format": "dialogue",
        "titleWord": "少子化の影響について話す",
        "titleJp": "少子化の影響について話す",
        "titleEn": "Discussing the impact of the declining birthrate",
        "titleZh": "聊少子化的影响",
        "titleRuby": [],
        "sections": [
            section("身近な変化", "Changes close to home", "身边的变化", "🏫", [
                ("A", "久しぶりに地元に帰ったら、母校の小学校がなくなっていて驚いた。",
                 "I was surprised when I went back to my hometown after a long time and found my old elementary school was gone.",
                 "好久没回老家，发现母校的小学没了，吓了一跳。"),
                ("B", "うちの近所でも、子どもの声がほとんど聞こえなくなったよ。",
                 "In my neighborhood too, you can barely hear children's voices anymore.",
                 "我家附近也几乎听不到孩子的声音了。"),
                ("A", "商店街も高齢者向けの店ばかりになって、雰囲気がすっかり変わった。",
                 "The shopping street has become almost all shops for the elderly — the atmosphere has completely changed.",
                 "商店街也全变成面向老年人的店了，气氛完全变了。"),
                ("B", "このまま進んだら、地方の町はどうなっちゃうんだろうね。",
                 "If this keeps going, what will happen to the rural towns?",
                 "这样下去的话，地方的小镇会变成什么样呢。"),
            ]),
            section("原因と対策", "Causes and solutions", "原因和对策", "💡", [
                ("A", "少子化の原因って、やっぱり経済的な理由が大きいのかな。",
                 "Is the main cause of the declining birthrate economic reasons after all?",
                 "少子化的原因，果然还是经济原因居多吗。"),
                ("B", "それもあるけど、働き方の問題も大きいと思う。育児と仕事の両立が本当に大変だから。",
                 "That too, but I think work-style issues are also big. Balancing childcare and work is really tough.",
                 "这也有，但工作方式的问题我觉得也很大。兼顾育儿和工作真的很难。"),
                ("A", "児童手当が増えたとはいえ、教育費を考えると二人目は厳しいって声も聞く。",
                 "Even though child allowances have increased, I hear people saying a second child is tough when you think about education costs.",
                 "虽然儿童津贴增加了，但考虑到教育费用，也听说生第二个很难。"),
                ("B", "社会の仕組みを根本から変えないと、出生率はなかなか上がらないだろうね。",
                 "Unless we fundamentally change the social system, the birth rate probably won't rise easily.",
                 "不从根本上改变社会的机制，出生率大概很难提高吧。"),
                ("A", "子育てしやすい環境を作ることが、結局は社会全体のためになるんだと思う。",
                 "Creating an environment where it's easy to raise children ultimately benefits society as a whole, I think.",
                 "我觉得营造一个容易养育孩子的环境，最终对整个社会都是有益的。"),
            ]),
        ],
    },
]


def main():
    path = ROOT / "public" / "data" / "ja_articles.json"
    data = json.loads(path.read_text("utf-8"))
    existing_ids = {it["id"] for it in data["items"]}

    added = 0
    for item in NEW_ITEMS:
        if item["id"] in existing_ids:
            print(f"  skip (exists): {item['id']}")
            continue

        # enrich segments
        if item["format"] == "essay":
            raw = item["segments"]
            item["segments"] = [enrich_segment(w, e, z) for w, e, z in raw]

        # enrich titleRuby
        item["titleRuby"] = gr.make_ruby(item["titleWord"])

        data["items"].append(item)
        added += 1
        print(f"  added: {item['id']} — {item['titleWord']}")

    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", "utf-8")
    print(f"\n合計 {added} 件追加しました。")


if __name__ == "__main__":
    main()
